/*
  Nunaliit2 Inuktitut Language Pack
*/
;(function($,$n2){

    $n2.l10n.addLocalizedStrings('iu',{
        // Language: iu
        "definition (":"ᑐᑭᓕᐅᕐᓂᖅ ("
        ,"definition (index: ":"ᑐᑭᓕᐅᕐᓂᖅ (ᐃᓗᓕᖏᑦ: "
        ,"definition null and skipped.":"ᑐᑭᐅᔪᖅ ᐱᑕᖃᙱᑦᑐᖅ ᐊᒻᒪᓗ ᖄᖏᖅᑕᐅᔪᖅ."
        ,"definition: ":"ᑐᑭᓕᐅᕐᓂᖅ: "
        ,"(by {author})":"(ᐆᒧᖓ {author})"
        ,"<Unknown error>":"<ᖃᐅᔨᒪᔭᐅᙱᑦᑐᖅ ᑕᒻᒪᖅᑐᖅ>"
        ,"<error>":"<ᑕᒻᒪᖅᑐᖅ>"
        ,"?":"?"
        ,"A HTML file must be specified for the customHtml canvas":"HTML ᑎᑎᖅᖃᖅ ᐅᖃᖅᑕᐅᓯᒪᔭᕆᐊᓕᒃ customHtml canvas-ᒧᑦ"
        ,"A SVG file must be specified for the customSvg canvas":"SVG ᑎᑎᖅᖃᖅ ᐅᖃᖅᑕᐅᓯᒪᔭᕆᐊᓕᒃ customSvg canvas-ᒧᑦ"
        ,"A database must be provided":"ᓈᓴᐅᑎᓄᑦ/ᑎᑎᖅᖃᓄᑦ ᑐᖅᖁᖅᓯᓯᒪᕝᕕᒃ ᑐᓂᔭᐅᔭᕆᐊᓕᒃ"
        ,"A document identifier must be provided":"ᑎᑎᖅᖃᕐᒥᑦ ᓇᓗᓇᐃᖅᓯᔾᔪᑎᒥᒃ ᑐᓂᓯᔭᕆᐊᓕᒃ"
        ,"A file must be selected":"ᑎᑎᖅᖃᒥᒃ ᓂᕈᐊᕆᐊᓕᒃ"
        ,"A filter function must be supplied":"ᕿᓂᖅᓴᐃᓂᕐᒧᑦ ᓇᓗᓇᐃᒃᑯᑦᑎᖅᓯᒪᔪᓄᑦ ᐊᑐᖅᑐᖅ ᑐᓂᔭᐅᔭᕆᐊᓕᒃ"
        ,"A list must be provided for refining":"ᑎᑎᕋᖅᓯᒪᔪᑦ ᑐᓂᔭᐅᔭᕆᐊᓖᑦ ᐱᐅᓯᒋᐊᕐᓂᐊᕐᓗᒍ"
        ,"A list name must be supplied":"ᑎᑎᕋᖅᓯᒪᔪᑦ ᐊᑏᑦ ᑐᓂᔭᐅᔭᕆᐊᓖᑦ"
        ,"A name must be provided when refining a list":"ᐊᑎᕐᒥᑦ ᑐᓂᓯᔭᕆᐊᓕᒃ ᐱᐅᓯᒋᐊᖅᓯᓂᐊᕐᓗᓂ ᑎᑎᕋᖅᓯᒪᔪᓂᒃ"
        ,"A valid schema must be provided":"ᐊᑐᖅᑐᒥᒃ ᐋᖅᕿᒃᓯᒪᔪᒥᒃ ᑐᓂᓯᔭᕆᐊᖃᖅᑐᖅ"
        ,"AUTO":"ᐃᖕᒥᓂᑦ"
        ,"Accept":"ᓈᒻᒪᒋᓗᒍ"
        ,"Accept User Agreement":"ᓈᒻᒪᒋᓗᒍ ᐊᑐᖅᑎᒧᑦ ᐊᖏᖃᑎᒌᒍᑎ"
        ,"Add":"ᐃᓚᓯᓂᖅ"
        ,"Add Comment":"ᐃᓚᓯᓗᓂ ᐅᖃᐅᓯᕐᒥᒃ"
        ,"Add File":"ᐃᓚᓯᓗᓂ ᑎᑎᖅᖃᒥᑦ"
        ,"Add Layer":"ᐃᓚᓯᓗᓂ ᖃᓪᓕᕐᒥᑦ"
        ,"Add Related Item":"ᐃᓚᓯᓗᓂ ᐱᔾᔪᑎᖃᖅᑐᒥᒃ"
        ,"Add Relation":"ᐃᓚᓯᓗᓂ ᐱᔾᔪᑕᐅᔪᒥᒃ"
        ,"Add User":"ᐃᓚᓯᓗᓂ ᐊᑐᖅᑎᒥᒃ"
        ,"Add a feature to the map based on a gazetteer service":"ᐃᓚᓯᓗᓂ ᐃᓚᒋᔭᐅᔪᒥᒃ ᓄᓇᙳᐊᒧᑦ ᒐᔭᑎᐅᕐ ᐱᔨᑦᑎᕋᐅᑎᒧᑦ"
        ,"Add a line to the map":"ᐃᓚᓯᓗᓂ ᑎᑯᓕᐊᖅᑐᒥᒃ ᓄᓇᙳᐊᒧᑦ"
        ,"Add a point to the map":"ᐃᓚᓯᓗᓂ ᓇᓗᓇᐃᖅᓯᒪᔪᒥᒃ ᓄᓇᙳᐊᒧᑦ"
        ,"Add a polygon to the map":"ᐃᓚᓯᓗᓂ ᓄᓗᓇᐃᒃᑯᑕᒥᒃ ᓄᓇᙳᐊᒧᑦ"
        ,"Add or Edit a Map Feature":"ᐃᓚᓯᓗᓂ ᐅᕝᕙᓘᓐᓃᑦ ᐋᖅᕿᒃᓯᓱᕐᓗᒍ ᓄᓇᙳᐊᒧᑦ ᐃᓚᒋᔭᐅᔪᖅ"
        ,"Alert":"ᖃᐅᔨᑎᑦᑎᔾᔪᑎ"
        ,"All":"ᑕᒪᕐᒥᑦ"
        ,"All Documents":"ᑕᒪᕐᒥᑦ ᑎᑎᖅᖃᐅᑏᑦ"
        ,"All Geometries":"ᑕᒪᕐᒥᑦ ᓈᓴᐅᓯᕆᓃᑦ"
        ,"All Layers":"ᑕᒪᕐᒥᑦ ᖃᓕᕇᑦ"
        ,"All LineString Geometries":"ᑕᒪᕐᒥᓗᒃᑖᖅ ᑎᑯᓕᐊᖅᑐᑦ ᐋᖅᕿᒃᓯᒪᔪᑦ ᓈᓴᐅᑎᓄᑦ/ᑎᑎᖅᖃᓄᑦ ᓈᓴᐅᓯᕆᓃᑦ"
        ,"All Point Geometries":"ᑕᒪᕐᒥᑦ ᓄᓇᙳᐊᒥᑦ ᓇᓗᓇᐃᖅᓯᔪᑦ ᓈᓴᐅᓯᕆᓃᑦ"
        ,"All Polygon Geometries":"ᑕᒪᕐᒥᑦ ᓇᓗᓇᐃᒃᑯᑕᓄᑦ ᓈᓴᐅᓯᕆᓃᑦ"
        ,"All documents containing {searchTerm}":"ᑕᒪᕐᒥᑦ ᑎᑎᖅᖃᐅᑏᑦ ᐃᓗᓕᖃᖅᑐᑦ {searchTerm}"
        ,"All documents filtered by script":"ᑕᒪᕐᒥᑦ ᑎᑎᖅᖃᐅᑏᑦ ᕿᓂᖅᓴᐃᓂᕐᒧᑦ ᓇᓗᓇᐃᒃᑯᑦᑎᖅᓯᒪᔪᑦ ᑎᑎᕋᖅᓯᒪᓂᒃᑯᑦ"
        ,"All documents matching regex {regex}":"ᑕᒪᕐᒥᑦ ᑎᑎᖅᖃᐅᑏᑦ ᐊᔾᔨᖏᓐᓂᒃ ᑎᑎᖅᖃᖃᖅᑐᑦ {regex} "
        ,"An import profile must be provided":"ᐃᓕᓗᒍ ᐱᔾᔪᑎᖃᖅᑐᒥᒃ ᐃᓚᐅᔪᖃᕆᐊᖃᖅᑐᖅ"
        ,"Approve":"ᓈᒻᒪᒃᓴᖅᑐᖓ"
        ,"Attach":"ᐃᓕᓗᒍ"
        ,"Attachment":"ᐃᓚᐅᖃᑕᐅᔪᖅ"
        ,"Attachment Name":"ᐃᓚᐅᖃᑕᐅᔫᑉ ᐊᑎᖓ"
        ,"Attachment has been denied":"ᐃᓚᐅᖃᑕᐅᔪᖅ ᕿᐱᓗᒃᑕᐅᔪᖅ"
        ,"Attachment is being processed":"ᐃᓕᐅᖃᑕᐅᔪᖅ ᐱᓕᕆᐊᖑᔪᖅ"
        ,"Attachment is waiting for approval":"ᐃᓚᐅᖃᑕᐅᔪᖅ ᓈᒻᒪᒋᔭᐅᓂᕐᒧᑦ ᐅᑕᖅᕿᔪᖅ"
        ,"Attachment: ":"ᐃᓚᐅᖃᑕᐅᔪᖅ: "
        ,"Authentication service must be configured":"ᓇᓚᐅᑦᑎᓂᕐᒧᑦ ᐱᔨᑦᑎᕋᐅᑎ ᐋᖅᕿᒃᓱᖅᑕᐅᔭᕆᐊᖃᖅᑐᖅ"
        ,"Author":"ᑎᑎᕋᖅᑎ"
        ,"Available Layers":"ᒪᓂᒪᔪᑦ ᖃᓕᕇᒃᑐᑦ"
        ,"Back":"ᐅᑎᕐᓗᓂ"
        ,"Bad Proxy Circumvention":"ᐱᑦᑕᐅᖏᑦᑐᖅ ᐊᓯᐊᓄᐊᖅᑐᒥᒃ ᐊᔪᖅᑎᑦᑎᔪᖅ"
        ,"Base Layer":"ᑐᙵᕕᒃ ᖃᓕᕇᖓᔪᖅ"
        ,"Body":"ᑎᒥᖓ"
        ,"Brief":"ᓇᐃᑦᑐᖅ"
        ,"By":"ᐅᕗᖓ"
        ,"COLLISION":"ᑲᑎᓐᓃᑦ"
        ,"CSS":"CSS"
        ,"CSV":"CSV"
        ,"Can not find import profile with id: {id}":"ᓇᓂᓂᖅ ᐊᔪᕐᓇᖅᑐᖅ ᐃᓕᓗᒍ ᐱᔾᔪᑎᖃᖅᑐᖅ ᓇᓗᓇᐃᖅᓯᔾᔪᑎᒧᑦ: {id}"
        ,"Can not parse date":"ᐊᔪᕐᓇᖅᑐᖅ ᐅᖃᐅᓯᕆᓂᖅ ᐅᑉᓗᖅ"
        ,"Can not perform file uploads unless jquery.form.js is included":"ᑎᑎᖅᖃᓂᒃ ᐊᐅᓪᓚᐃᓂᖅ ᐊᔪᕐᓇᖅᑐᖅ ᑭᓯᐊᓂ jquery.form.js ᐃᓚᐅᒃᐸᑦ"
        ,"Cancel":"ᓄᖅᖃᖅᑎᓐᓂᖅ"
        ,"Cancel Feature Editing":"ᓄᖅᖃᖅᑎᓪᓗᒍ ᐃᓚᒋᔭᐅᔪᒥᒃ ᐋᖅᕿᒃᓱᐃᓂᖅ"
        ,"Cancelling Operation...":"ᓄᖅᖃᖅᑎᑕᐅᔪᖅ ᐊᐅᓛᖅᑎᑦᑎᓂᖅ..."
        ,"Capture Photo":"ᐱᓗᒍ ᐊᔾᔨ"
        ,"Capture Video":"ᐱᓗᒍ ᐊᐅᓚᔪᖅ ᑕᕐᕆᔭᐅᑎ"
        ,"Capture Audio":"ᐱᓗᒍ ᓂᐱᖃᖅᑐᖅ"
        ,"Change Password":"ᐊᓯᐊᙳᕐᓗᒍ ᑕᐃᑯᙵᕈᖕᓇᐅᑎ"
        ,"Choose File":"ᓂᕈᐊᕐᓗᒍ ᑎᑎᖅᖃᖅ"
        ,"Clear":"ᑕᑯᒃᓴᐅᔪᖅ"
        ,"Click here to return to main site: ":"ᓇᕿᓪᓗᒍ ᐅᓇ ᐅᑎᕐᓂᐊᕐᓗᑎᒃ ᐱᒋᐊᕐᕕᐅᖅᖃᐅᑕᐅᔪᒧᑦ: "
        ,"Close":"ᐊᑭᑐᓗᐊᖏᑦᑐᖅ ᒪᓕᖕᓂᕐᒧᑦ"
        ,"Collision on Geometry":"ᑲᑎᓐᓂᖅ ᓈᓴᐅᓯᕆᓂᕐᒥᑦ"
        ,"Collision on property {property}":"ᑲᑎᓐᓂᖅ ᐱᒋᔭᐅᔪᒧᑦ {property}"
        ,"Commands for removal":"ᐱᖁᔨᓃᑦ ᐲᖅᓯᓂᐊᕐᓗᓂ"
        ,"Comment":"ᐅᖃᐅᓯᒃᓴᑦ"
        ,"Compiling records":"ᑲᑎᑦᑎᓂᖅ ᑎᑎᖅᖃᐅᑎᓂᒃ"
        ,"Configuration":"ᐋᖅᕿᒃᓱᐃᓂᖅ"
        ,"Confirm":"ᓇᓗᓇᐃᕐᓗᒍ "
        ,"Confirm password:":"ᓇᓗᓇᐃᕐᓗᒍ ᑕᐃᑯᙵᕈᖕᓇᐅᑎ:"
        ,"Contact Information":"ᑐᑭᓯᒋᐊᕐᕕᒃᓴᐃᑦ ᑐᕌᕈᑎᖏᑦ"
        ,"Content":"ᐃᓗᓕᖏᑦ"
        ,"Contribution":"ᑐᓂᕐᕈᓯᐊᖅ"
        ,"Converted":"ᐊᓯᐊᙳᖅᑕᐅᔪᖅ"
        ,"Create Document":"ᓴᖅᕿᑦᑎᓗᓂ ᑎᑎᖅᖃᒥᑦ"
        ,"Create User":"ᓴᖅᕿᑦᑎᓗᓂ ᐊᑐᖅᑎᒥᒃ"
        ,"Create a new user":"ᓴᖅᕿᑦᑎᓗᓂ ᓄᑖᒥᒃ ᐊᑐᖅᑎᒥᒃ"
        ,"Create feature from name":"ᓴᖅᕿᑦᑎᓗᓂ ᐃᓚᒋᔭᐅᔪᒥᒃ ᐊᑎᕐᒥ ᐱᓗᒍ"
        ,"Create new document":"ᓴᖅᕿᑦᑎᓗᓂ ᓄᑖᖅ ᑎᑎᖅᖃᒥᒃ"
        ,"Create {label}":"ᓴᖅᕿᑦᑎᓗᓂ {label}"
        ,"Created by":"ᓴᖅᕿᑎᑕᐅᔪᖅ ᐆᒧᖓ"
        ,"Created document with id: {id}":"ᓴᖅᕿᑦᑎᓗᓂ ᑎᑎᖅᖃᒥᒃ ᓇᓗᓇᐃᖅᓯᔾᔪᑎᖃᖅᑐᖅ: {id}"
        ,"Creating a user associated with the e-mail address: {address}":"ᓴᖅᕿᑦᑎᓂᖅ ᐊᑐᖅᑎᒥᒃ ᐊᒃᑐᐊᓂᖃᖅᑐᒥᒃ ᖃᕆᑕᐅᔭᒃᑯᑦ ᑎᑎᖅᖃᒧᑦ ᑐᕌᕈᑎᒥᑦ: {address}"
        ,"Current Location":"ᒫᓐᓇᐅᔪᖅ ᐃᓂᐅᔪᖅ"
        ,"Custom Script":"ᐋᖅᕿᒋᐊᓕᒃ ᑎᑎᕋᖅᓯᒪᔪᖅ"
        ,"Data Modification Application":"ᓈᓴᐅᑎᓂᒃ/ᑎᑎᖅᖃᓂᒃ ᐋᖅᕿᒋᐊᖅᓯᓂᕐᒧᑦ ᐊᑐᖅᑐᖅ"
        ,"Date":"ᐅᑉᓗᖅ"
        ,"Debug Application":"ᖁᐱᕐᕈᐃᔭᕐᓗᒍ ᐊᑐᖅᑐᖅ"
        ,"Debug Configuration":"ᖁᐱᕐᕈᐃᔭᕐᓗᒍ ᐋᖅᕿᒃᓱᐃᓂᖅ"
        ,"Default":"ᐊᑐᖅᑕᐅᖃᑦᑕᖅᑐᖅ"
        ,"Delete":"ᐲᕐᓗᒍ"
        ,"Delete Database Document":"ᐲᕐᓗᒍ ᓈᓴᐅᑎᓄᑦ/ᑎᑎᖅᖃᓄᑦ ᑐᖅᖁᖅᓯᓯᒪᕝᕕᖕᒦᑦᑐᖅ ᑎᑎᖅᖃᖅ"
        ,"Delete document":"ᐲᕐᓗᒍ ᑎᑎᖅᖃᖅ"
        ,"Delete existing document":"ᐲᕐᓗᒍ ᑕᐃᒪᐅᔪᖅ ᑎᑎᖅᖃᖅ"
        ,"Deleted document with id: {id}":"ᐲᖅᑐᖅ ᑎᑎᖅᖃᖅ ᓇᓗᓇᐃᖅᓯᔾᔪᑎᖃᖅᑐᖅ: {id}"
        ,"Deletion Progress":"ᐲᖅᑕᐅᕙᓪᓕᐊᔪᖅ"
        ,"Demo Document":"ᐆᒃᑐᕋᐅᑎ ᑎᑎᖅᖃᖅ"
        ,"Demo Media":"ᐆᒃᑐᕋᐅᑎ ᖃᕆᑕᐅᔭᒧᑦ ᐃᓚᒋᔭᐅᔪᖅ"
        ,"Deny":"ᕿᐱᓗᒡᓗᒍ"
        ,"Description":"ᖃᓄᐃᑦᑑᓂᖓ"
        ,"Disable":"ᓄᖅᖃᖅᑎᓪᓗᒍ"
        ,"Discard":"ᐊᒃᑕᑰᕐᓗᒍ"
        ,"Dispatcher Event Logging":"ᑲᒪᔨ ᐱᓕᕆᐊᒧᑦ ᑕᐃᑯᙵᖅᑐᖅ"
        ,"Display":"ᑕᑯᒃᓴᐅᓗᒍ"
        ,"Display Name":"ᑕᑯᒃᓴᐅᓗᒍ ᐊᑎᖅ"
        ,"Do not show again":"ᑕᑯᒃᓴᐅᑎᒃᑲᓐᓂᖅᑕᐃᓕᓕ"
        ,"Do not show this warning again":"ᑕᑯᒃᓴᐅᑎᒃᑲᓐᓂᖅᑕᐃᓕᓕ ᐅᔾᔨᖅᑐᖁᔨᔪᖅ"
        ,"Do you really want to delete this feature?":"ᐲᕈᒪᕕᐅᒃ ᐃᓚᒋᔭᐅᔪᖅ?"
        ,"Do you really wish to delete the {count} document(s) referenced by this list?":"ᐱᕈᒪᕕᒋᑦ {count} ᑎᑎᖅᖃᖅ(ᐃᑦ) ᐅᖃᐅᓯᐅᔪᑦ ᑎᑎᕋᖅᓯᒪᔪᓄᑦ?"
        ,"Do you wish to delete this element?":"ᐲᕈᒪᕕᐅᒃ ᐃᓚᒋᔭᐅᔪᖅ?"
        ,"Do you wish to leave document editor?":"ᕿᒪᒍᒪᕕᐅᒃ ᑎᑎᖅᖃᒥᒃ ᐋᖅᕿᒃᓱᐃᔾᔪᑎ?"
        ,"Doc ids must be supplied when creating a list from document ids":"ᑎᑎᖅᖃᓂᒃ ᓇᓗᓇᐃᖅᓯᔾᔪᑏᑦ ᑐᓂᔭᐅᔭᕆᐊᖃᖅᑐᑦ ᓴᖅᕿᑦᑎᓂᐊᕐᓗᓂ ᑎᑎᕋᖅᓯᒪᔪᓂᒃ ᑎᑎᖅᖃᓂᒃ ᓇᓗᓇᐃᖅᓯᔾᔪᑎᓂᒃ"
        ,"Document Id":"ᑎᑎᖅᖃᓂᒃ ᓇᓗᓇᐃᖅᓯᔾᔪᑎ"
        ,"Document Identifiers":"ᑎᑎᖅᖃᓂᒃ ᓇᓗᓇᐃᖅᓯᔾᔪᑏᑦ"
        ,"Document was modified and changes will be lost. Do you wish to continue?":"ᑎᑎᖅᖃᖅ ᐋᖅᕿᒋᐊᖅᑕᐅᓚᐅᖅᑐᖅ ᐊᒻᒪᓗ ᐊᓯᐊᙳᖅᑐᑦ ᐊᓯᐅᔨᓂᐊᖅᑐᑦ. ᑲᔪᓯᔪᒪᕕᑦ?"
        ,"Document: {id}":"ᑎᑎᖅᑲᖅ: {id}"
        ,"Documents from import profile: {profileId}":"ᑎᑎᖅᖃᐃᑦ ᐃᓕᓗᒍ ᐱᔾᔪᑎᖃᖅᑐᒥᑦ: {profileId}"
        ,"Documents from layer {layerName}":"ᑎᑎᖅᖃᐃᑦ ᖃᓕᕇᒥᑦ {layerName}"
        ,"Documents from schema type {schemaName}":"ᑎᑎᖅᖃᐅᑏᑦ ᐋᖅᕿᒃᓯᒪᔪᑦ ᖃᓄᐃᑦᑑᓂᖏᓐᓄᑦ {schemaName}"
        ,"Documents from view {label}":"ᑎᑎᖅᖃᐃᑦ ᑕᑯᒃᓴᐅᓂᕐᒥᑦ {label}"
        ,"Documents not reachable by reference":"ᑎᑎᖅᖃᐃᑦ ᑎᑭᐅᑎᔭᐅᓂᖅ ᐊᔪᖅᑐᑦ ᐱᔾᔪᑕᐅᔪᒃᑯᑦ "
        ,"Documents referencing {docId}":"ᑎᑎᖅᖃᓂᒃ ᐱᔾᔪᑕᐅᔪᓕᐅᕆᓂᖅ {docId}"
        ,"Documents that are invalid":"ᑎᑎᖅᖃᐃᑦ ᐊᔪᖅᑐᑦ"
        ,"Documents that have an invalid source":"ᑎᑎᖅᖃᐃᑦ ᐊᔪᖅᑐᓂᒃ ᐱᕝᕕᐅᔪᖃᖅᑐᑦ"
        ,"Documents with dangling references":"ᑎᑎᖅᖃᐃᑦ ᐊᐅᓚᒪᑦᑐᓂᒃ ᐱᔾᔪᑕᐅᔪᖃᖅᑐᑦ"
        ,"Documents with media files in analyzed state":"ᑎᑎᖅᖃᐃᑦ ᖃᕆᑕᐅᔭᒧᑦ ᐃᓚᒋᔭᐅᔪᓂᑦ ᑎᑎᖅᖃᖃᖅᑐᑦ ᖃᐅᔨᓴᐃᓂᕐᒦᖦᖢᑎᒃ"
        ,"Documents with media files in approved state":"ᑎᑎᖅᖃᐃᑦ ᖃᕆᑕᐅᔭᒧᑦ ᐃᓚᒋᔭᐅᔪᓂᑦ ᑎᑎᖅᖃᖃᖅᑐᑦ ᓈᒻᒪᒋᔭᐅᑉᓗᓂ"
        ,"Documents with media files in attached state":"ᑎᑎᖅᖃᐃᑦ ᖃᕆᑕᐅᔭᒧᑦ ᐃᓚᒋᔭᐅᔪᓂᑦ ᑎᑎᖅᖃᖃᖅᑐᑦ ᐃᓚᓕᐅᑎᓯᒪᑉᓗᓂ"
        ,"Documents with media files in submitted state":"ᑎᑎᖅᖃᐃᑦ ᖃᕆᑕᐅᔭᒧᑦ ᐃᓚᒋᔭᐅᔪᓂᑦ ᑎᑎᖅᖃᖃᖅᑐᑦ ᑐᓂᔭᐅᑉᓗᓂ"
        ,"Documents with media files in waiting state":"ᑎᑎᖅᖃᐃᑦ ᖃᕆᑕᐅᔭᒧᑦ ᐃᓚᒋᔭᐅᔪᓂᑦ ᑎᑎᖅᖃᖃᖅᑐᑦ ᐅᑕᖅᕿᑉᓗᓂ"
        ,"Done":"ᐱᐊᓂᒃᑐᖅ"
        ,"Done.":"ᐱᐊᓂᒃᑐᖅ."
        ,"Download":"ᖃᕆᑕᐅᔭᒃᑯᑦ ᐱᓗᒍ"
        ,"E-Mail address must be specified":"ᖃᕆᑕᐅᔭᒃᑯᑦ ᑎᑎᖅᖃᒧᑦ ᑐᕌᕈᑎ ᐅᖃᖅᑕᐅᓯᒪᔭᕆᐊᖃᖅᑐᖅ"
        ,"E-mail":"ᖃᕆᑕᐅᔭᒃᑯᑦ ᑐᕌᕈᑎ"
        ,"E-mail Form":"ᖃᕆᑕᐅᔭᒃᑯᑦ ᑎᑎᖅᖃᒧᑦ ᑐᕌᕈᑎᒧᑦ ᑕᑕᑎᕆᐊᓕᒃ"
        ,"E-mail Template":"ᖃᕆᑕᐅᔭᒃᑯᑦ ᑎᑎᖅᖃᒧᑦ ᐊᑐᖅᑕᐅᔪᒃᓴᖅ"
        ,"E-mail addresses":"ᖃᕋᓴᐅᔭᒃᑯᑦ ᑎᑎᖅᑲᒃᑯᕕᖓ"
        ,"E-mail me my password":"ᖃᕆᑕᐅᔭᒃᑯᑦ ᑎᑎᖅᖃᑎᒍᑦ ᐊᐅᓪᓚᖅᑎᕝᕕᒋᙵ ᑕᐃᑯᙵᕈᖕᓇᐅᑎᒻᓂᒃ"
        ,"E-mails":"ᖃᕆᑕᐅᔭᒃᑯᑦ ᑎᑎᖅᖃᐃᑦ"
        ,"Edit":"ᐋᖅᕿᒃᓱᕐᓗᒍ"
        ,"Edit Proposed Document":"ᐋᖅᕿᒃᓱᕐᓗᒍ ᑎᑎᖅᖃᐅᑎᓕᐊᖑᓂᐊᖅᑐᖅ"
        ,"Edit User":"ᐋᖅᕿᒃᓱᕐᓗᒍ ᐊᑐᖅᑎᐅᔪᖅ"
        ,"Editor View":"ᐋᖅᕿᒃᓱᕐᓗᒍ ᑕᑯᒃᓴᐅᓂᖅ"
        ,"Empty search results":"ᐃᓗᓖᕐᓗᒍ ᕿᓂᖅᓴᐃᓂᕐᒧᑦ ᖃᓄᐃᖓᓂᐅᔪᑦ"
        ,"Enable":"ᐱᒋᐊᖅᑎᓪᓗᒍ"
        ,"Enabled":"ᐱᒋᐊᖅᑎᑕᐅᔪᖅ"
        ,"Enter Report Script":"ᐃᓕᓗᒍ ᐅᓂᑉᑳᒧᑦ ᑎᑎᕋᖅᓯᒪᔪᖅ"
        ,"Enter password:":"ᐃᓕᓗᒍ ᑕᐃᑯᙵᕈᖕᓇᐅᑎ:"
        ,"Enter reason for rejecting submission":"ᐃᓕᓗᒍ ᐃᔾᔪᑕᐅᔪᖅ ᕿᐱᓗᒃᑕᐅᓂᖓ ᑐᓂᐅᑎᒋᔭᐅᓂᖅ"
        ,"Error":"ᑕᒻᒪᖅᑐᖅ"
        ,"Error attempting to accept user agreement":"ᑕᒻᒪᖅᑐᖅ ᓈᒻᒪᒋᒋᐊᖅᖢᒍ ᐊᑐᖅᑎᒧᑦ ᐊᖏᖃᑎᒌᒍᑎ"
        ,"Error creating ":"ᑕᒻᒪᖅᑐᖅ ᓴᖅᕿᑦᑎᓂᕐᒥᒃ "
        ,"Error creating document":"ᑕᒻᒪᖅᑐᖅ ᓴᖅᕿᑦᑎᓂᕐᒥᒃ ᑎᑎᖅᖃᒥᒃ"
        ,"Error creating import profile. Unknown operation string: {string}":"ᑕᒻᒪᖅᑐᖅ ᓴᖅᕿᑦᑎᓂᕐᒥᒃ ᐃᓕᓗᒍ ᐱᔾᔪᑎᖃᖅᑐᒥᒃ. ᖃᐅᔨᒪᔭᐅᖏᑦᑐᑦ ᐊᐅᓛᖅᑎᑦᑎᓂᕐᒧᑦ ᐋᖅᕿᒃᓯᒪᔪᖅ: {string}"
        ,"Error creating import profile: {err}":"ᑕᒻᒪᖅᑐᖅ ᓴᖅᕿᑦᑎᓂᕐᒥᒃ ᐃᓕᓗᒍ ᐱᔾᔪᑎᖃᖅᑐᒥᒃ: {err}"
        ,"Error deleting document":"ᑕᒻᒪᖅᑐᖅ ᐲᕆᐊᖅᖢᒍ ᑎᑎᖅᖃᖅ"
        ,"Error during export":"ᑕᒻᒪᖅᑐᖅ ᐊᐅᓪᓚᐃᓇᓱᒃᑎᓪᓗᒍ"
        ,"Error fetching attachment from help document":"ᑕᒻᒪᖅᑐᖅ ᐱᔭᖅᑐᖅᑎᓪᓗᒍ ᐃᓚᓕᐅᑎᓯᒪᔪᒥᒃ ᐃᑲᔪᖅᑐᖅ ᑎᑎᖅᖃᐅᑎᒥᑦ"
        ,"Error loading CSS from location: {url}":"ᑕᒻᒪᖅᑐᖅ ᐃᓕᔭᐅᓂᖓ CSS ᐃᓂᐅᔪᒥᑦ: {url}"
        ,"Error loading HTML from location: {url}":"ᑕᒻᒪᖅᑐᖅ ᐃᓕᔭᐅᓂᖓ HTML ᐃᓂᐅᔪᒥᑦ: {url}"
        ,"Error loading SVG from location: {url}":"ᑕᒻᒪᖅᑐᖅᐃᓕᔭᐅᓂᖓ SVG ᐃᓂᐅᔪᒥᑦ: {url}"
        ,"Error loading documents from database: {err}":"ᑕᒻᒪᖅᑐᖅ ᐃᓕᐅᖅᖃᐃᑉᓗᓂ ᑎᑎᖅᖃᐅᑎᓂᒃ ᓈᓴᐅᑎᓂᒃ/ᑎᑎᖅᖃᓂᒃ ᑐᖅᖁᖅᓯᓯᒪᕝᕕᖕᒥᑦ: {err}"
        ,"Error obtaining user document for {id}: {err}":"ᑕᒻᒪᖅᑐᖅ ᐱᓂᐊᕐᓗᓂ ᐊᑐᖅᑎᒧᑦ ᑎᑎᖅᖃᒥᑦ ᐅᕗᖓ {id}: {err}"
        ,"Error occurred after document was saved. Error: {err}":"ᑕᒻᒪᖅᖃᐅᔪᖅ ᑎᑎᖅᖃᖅ ᐊᓯᐅᔨᑦᑕᐃᓕᔭᐅᖅᖄᖅᑎᓪᓗᒍ. ᑕᒻᒪᖅᑐᖅ: {err}"
        ,"Error occurred after related document was created. Error: {err}":"ᑕᒻᒪᖅᑐᖅ ᑭᖑᓂᐊᒍᑦ ᐱᔾᔪᑎᖃᖅᑐᖅ ᑎᑎᖅᖃᖅ ᓴᖅᕿᑕᐅᖕᒪᑦ. ᑕᒻᒪᖅᑐᖅ: {err}"
        ,"Error occurred with progress service":"ᑕᒻᒪᖅᑐᖅ ᐱᕙᓪᓕᐊᔪᖅ ᐱᔨᑦᑎᕋᐅᑎᒧᑦ"
        ,"Error reloading conflicting document during deletion":"ᑕᒻᒪᖅᑐᖅ ᐃᓕᔭᐅᒃᑲᓐᓂᕋᓱᒃᖢᓂ ᐃᖢᐃᓗᑕᖅ ᑎᑎᖅᖃᖅ ᐲᖅᑕᐅᑎᓪᓗᒍ"
        ,"Error updating document":"ᑕᒻᒪᖅᑐᖅ ᓄᑖᙳᖅᑎᖅᑕᐅᔪᖅ ᑎᑎᖅᖃᖅ"
        ,"Error while analyzing import: {err}":"ᑕᒻᒪᖅᑐᖅᖃᐅᔨᓴᐃᑎᓪᓗᒍ ᐃᓕᔭᐅᔪᒥᒃ: {err}"
        ,"Error while updating document {id}":"ᑕᒻᒪᖅᑐᖅ ᓄᑖᙳᖅᑎᕆᑎᓪᓗᒍ ᑎᑎᖅᖃᒥᒃ {id}"
        ,"Error while uploading: ":"ᑕᒻᒪᖅᑐᖅ ᐊᐅᓪᓚᐃᓇᓱᒃᑎᓪᓗᒍ: "
        ,"Error: query error while verifying {label} definition ({key})":"ᑕᒻᒪᖅᑐᖅ: ᐊᐱᖅᖁᑎ ᑕᒻᒪᖅᑐᖅ ᓇᓗᓇᐃᔭᐃᑎᓪᓗᒍ {label} ᑐᑭᐅᔪᒥᒃ ({key})"
        ,"Errors in process: {count}.":"ᑕᒻᒪᖅᓯᒪᔪᑦ ᐱᕙᓪᓕᐊᔪᑦ: {count}."
        ,"Export":"ᐊᐅᓪᓚᖅᑎᓪᓗᒍ"
        ,"Export Error":"ᐊᐅᓪᓚᖅᑎᓪᓗᒍ ᑕᒻᒪᖅᓯᒪᔪᖅ"
        ,"Export Geometries":"ᐊᐅᓪᓚᖅᑎᓪᓗᒋᑦ ᓈᓴᐅᓯᕆᓃᑦ"
        ,"Export by Script":"ᐊᐅᓪᓚᖅᑎᓪᓗᒍ ᑎᑎᕋᖅᓯᒪᔪᒃᑯᑦ"
        ,"Export service is not available":"ᐊᐅᓪᓚᖅᑎᓪᓗᒍ ᐱᔨᑦᑎᕋᐅᑎ ᒪᓂᒪᙱᑦᑐᖅ"
        ,"Export service is not configured":"ᐊᐅᓪᓚᖅᑎᓪᓗᒍ ᐱᔨᑦᑎᕋᐅᑎ ᐋᖅᕿᒃᓱᖅᓯᒪᙱᑦᑐᖅ"
        ,"Exporting":"ᐊᐅᓪᓚᖅᑎᑕᐅᕙᓪᓕᐊᔪᖅ"
        ,"Extent (Max X)":"ᑎᑭᐅᑎᓂᖓ (ᐊᖏᓛᖅ X)"
        ,"Extent (Max Y)":"ᑎᑭᐅᑎᓂᖓ (ᐊᖏᓛᖅ Y)"
        ,"Extent (Min X)":"ᑎᑭᐅᑎᓂᖓ (ᒥᑭᓛᖅ X)"
        ,"Extent (Min Y)":"ᑎᑭᐅᑎᓂᖓ (ᒥᑭᓛᖅ Y)"
        ,"Failure to delete {docId}":"ᐊᔪᖅᑐᖅ ᐲᖅᑕᐅᓂᖅ {docId}"
        ,"Failure to fetch {docId}":"ᐊᔪᖅᑐᖅ ᐱᔭᐅᔭᖅᑐᕐᓂᖅ {docId}"
        ,"Failure to save {docId}":"ᐊᔪᖅᑐᖅ ᐊᓯᐅᔨᔭᐅᑦᑕᐃᓕᓂᕐᒧᑦ {docId}"
        ,"Fetching All Document Ids":"ᐱᔭᐅᔭᖅᑐᖅᑐᑦ ᑕᒪᕐᒥᓗᒃᑖᑦ ᑎᑎᖅᖃᐅᑎᓄᑦ ᓇᓗᓇᐃᖅᓯᔾᔪᑏᑦ"
        ,"File":"ᑎᑎᖅᑲᖅ"
        ,"File Name":"ᑎᑎᖅᑲᐅᑉ ᐊᑎᖓ"
        ,"File Name:":"ᑎᑎᖅᑲᐅᑉ ᐊᑎᖓ:"
        ,"File Uploaded":"ᑎᑎᖅᖃᖅ ᐊᐅᓪᓚᖅᑎᑕᐅᔪᖅ"
        ,"File is not currently available":"ᑎᑎᖅᖃᖅ ᒫᓐᓇᐅᔪᖅ ᒪᓂᒪᙱᑦᑐᖅ"
        ,"Fill Out Related Document":"ᑕᑕᑎᕐᓗᒍ ᐱᔾᔪᑕᐅᔪᒧᑦ ᑎᑎᖅᖃᖅ"
        ,"Fill Out Reply":"ᑕᑕᑎᕐᓗᒍ ᑭᐅᓂᐊᕐᓗᓂ"
        ,"Fill out content of new document":"ᑕᑕᑎᕐᓗᒍ ᐃᓗᐊᓃᑦᑐᑦ ᓄᑖᖅ ᑎᑎᖅᖃᐅᑎᒥᑦ"
        ,"Filter:":"ᕿᓂᖅᓴᐃᓂᕐᒧᑦ ᓇᓗᓇᐃᒃᑯᑦᑎᖅᓯᒪᔪᑦ:"
        ,"Find on Map":"ᓇᓂᓗᒍ ᓄᓇᙳᐊᒥᑦ"
        ,"First Name":"ᓯᕗᓪᓕᖅᐹᖅ ᐊᑎᖓ"
        ,"Form":"ᑕᑕᑎᕆᐊᓕᒃ"
        ,"Form View":"ᑕᑕᑎᕆᐊᓕᒃ ᑕᑯᒃᓴᐅᔪᖅ"
        ,"Format:":"ᐋᖅᕿᐅᒪᓂᖓ:"
        ,"From":"ᐅᕙᙵᑦ"
        ,"Function Transformation":"ᐊᑐᖅᑐᖅ ᐊᓯᐊᙳᖅᓯᓂᕐᒧᑦ"
        ,"Function is required on transformation":"ᐊᑐᖅᑐᖅ ᐱᔭᕆᐊᖃᖅᑐᖅ ᐊᓯᐊᙳᖅᓯᓂᕐᒧᑦ"
        ,"GeoJSON definition must include an array named 'features'":"GeoJSON ᑐᑭᐅᔪᒥᑦ ᐃᓚᐅᔭᕆᐊᖃᖅᑐᖅ ᐋᖅᕿᑦᑎᐊᖅᓯᒪᔪᒥᒃ ᐊᑎᕐᒥᑦ 'ᐃᓚᒋᔭᐅᔪ'"
        ,"GeoJSON import is supported only for type 'FeatureCollection'":"GeoJSON ᒧᐊᖅᓯᓂᖅ ᐃᑲᔪᖅᑕᐅᔪᑦ ᖃᓄᐃᑦᑑᓂᖓᓄᑦ 'ᐃᓚᒋᔭᐅᔪᒥᒃ ᑲᑎᖅᓱᐃᓂᖅ'-ᒧᑦ"
        ,"Geometries":"ᓈᓴᐅᓯᕆᓃᑦ"
        ,"Geometries from layer {layerName}":"ᓈᓴᐅᓯᕆᓃᑦ {layerName}"
        ,"Geometry":"ᓈᓴᐅᓯᕆᓂᖅ"
        ,"Get a different password":"ᐊᓯᐊᓂᒃ ᑕᐃᑯᙵᕈᖕᓇᐅᑎᒥᒃ ᐱᓗᑎᑦ"
        ,"Graph application started":"ᑎᑎᕋᐅᔭᖅᓯᒪᔪᖅ ᐱᒋᐊᖅᑎᑕᐅᔪᑦ"
        ,"Guest Login":"ᐊᑐᖅᑎ ᑕᐃᑯᙵᕐᓂᐊᕐᓗᓂ"
        ,"Help":"ᐃᑲᔪᖅᑕᐅᒋᑦ"
        ,"Hover Sound":"ᖁᓛᓂᑦ ᐊᐅᓚᑲᑕᒡᓗᓂ ᓂᐱᖓ"
        ,"Hover Sound?":"ᖁᓛᓂᑦ ᐊᐅᓚᑲᑕᒡᓗᓂ ᓂᐱᖓ?"
        ,"I have forgotten my password":"ᐳᐃᒍᖅᑕᕋ ᑕᐃᑯᙵᕈᖕᓇᐅᑎᒐ"
        ,"I want to choose my own password":"ᓇᖕᒥᓂᖅ ᑕᐃᑯᙵᕈᖕᓇᐅᑎᒥᒃ ᓂᕈᐊᕈᒪᔪᖓ"
        ,"ID":"ᓇᓗᓇᐃᖅᓯᔾᔪᑎ"
        ,"Identifier":"ᓇᓗᓇᐃᖅᓯᔾᔪᑎ"
        ,"Import Profile":"ᐃᓕᓗᒍ ᐱᔾᔪᑎᖃᖅᑐᖅ"
        ,"Import data must be provided":"ᐃᓕᓗᒋᑦ ᓈᓴᐅᑏᑦ/ᑎᑎᖅᖃᐃᑦ ᑐᓂᔭᐅᔭᕆᐊᓕᒃ"
        ,"Imported entry does not contains an id attribute":"ᐃᓕᔭᐅᔪᑦ ᑎᑎᕋᖅᑕᐅᔪᖅ ᐃᓗᓕᖃᙱᑦᑐᖅ ᓇᓗᓇᐃᖅᓯᓂᕐᒧᑦ ᐊᑐᖅᑐᒥᒃ"
        ,"In reply to":"ᑭᐅᓗᓂ ᐅᕗᖓ"
        ,"Information to contact you":"ᑐᑭᓯᐅᒪᔾᔪᑏᑦ ᖃᐅᔨᒋᐊᕐᕕᐅᓂᐊᕐᓗᑎᑦ"
        ,"Inline":"ᑎᑯᓕᐊᖅᑐᖅ"
        ,"Input":"ᑭᐅᔾᔪᑕᐅᔪᖅ"
        ,"Interval":"ᓄᖅᖃᖓᓂᖅ"
        ,"Interval max must be a number":"ᓄᖅᖃᖓᓂᕐᓄᑦ ᐊᒥᓲᓛᖑᔭᕆᐊᓖᑦ ᓈᓴᐅᑎᐅᔭᕆᐊᓕᒃ"
        ,"Interval min can not be greater than max":"ᓄᖅᖃᖓᓂᖅ ᒥᑭᓛᒃᑯᑦ ᐊᖏᓂᖅᓴᐅᓂᖅ ᐊᖏᓛᖑᔪᒥᑦ ᐊᔪᖅᑐᖅ"
        ,"Interval min must be a number":"ᓄᖅᖃᖓᓂᖅ ᒥᑭᓛᒃᑯᑦ ᓈᓴᐅᑎᐅᔭᕆᐊᓕᒃ"
        ,"Introduction":"ᓇᓗᓇᐃᔭᐃᓂᖅ"
        ,"Invalid attachment in help document":"ᐊᑐᙱᑦᑐᖅ ᐃᓚᐅᑎᑕᐅᔪᖅ ᐃᑲᔪᖅᑐᖅ ᑎᑎᖅᖃᐅᑎᒥᑦ"
        ,"Invalid content in help document":"ᐊᑐᙱᑦᑐᖅ ᐃᓗᓕᖏᓐᓃᑦᑐᑦ ᐃᑲᔪᖅᑐᖅ ᑎᑎᖅᖃᐅᑎᒥᑦ"
        ,"Invalid date structure":"ᐊᑐᙱᑦᑐᖅ ᐅᑉᓗᖅ ᐋᖅᕿᒃᓯᒪᓂᖓ"
        ,"Invalid date: {err}":"ᐊᑐᙱᑦᑐᖅ ᐅᑉᓗᖅ: {err}"
        ,"Invalid document":"ᐊᑐᙱᑦᑐᖅ ᑎᑎᖅᖃᖅ"
        ,"Invalid e-mail and/or password":"ᐊᑐᙱᑦᑐᖅ ᖃᕆᑕᐅᔭᒃᑯᑦ ᑎᑎᖅᖃᓄᑦ ᑐᕌᕈᑎ ᐊᒻᒪᓗ/ᐅᕝᕙᓘᓐᓃᑦ ᑕᐃᑯᙵᕈᖕᓇᐅᑎ"
        ,"Invalid help document content":"ᐊᑐᙱᑦᑐᖅ ᐃᑲᔪᖅᑐᖅ ᑎᑎᖅᖃᐅᑎᒥᑦ ᐃᓗᐊᓃᑦᑐᑦ"
        ,"Invalid help document: {docId}":"ᐊᑐᙱᑦᑐᖅ ᐃᑲᔪᖅᑐᖅ ᑎᑎᖅᖃᐅᑎᒥᑦ: {docId}"
        ,"Invalid result returned by GeoNames":"ᐊᑐᙱᑦᑐᖅ ᖃᓄᐃᖓᓂᖅ ᐅᑎᖅᑎᑕᐅᔪᖅ GeoNames-ᒥᑦ"
        ,"Invalid search results returned":"ᐊᑐᙱᑦᑐᖅ ᕿᓂᖅᓴᐃᓂᖅ ᖃᓄᐃᖓᓂᐅᔪᓄᑦ ᐅᑎᖅᑎᑕᐅᔪᖅ"
        ,"Invalid server response":"ᐊᑐᙱᑦᑐᖅ ᐱᔨᑦᑎᖅᑐᖅ ᑭᐅᔪᖅ"
        ,"Invalid submission document":"ᐊᑐᙱᑦᑐᖅ ᑐᓂᔭᐅᔪᖅ ᑎᑎᖅᖃᖅ"
        ,"It appears that {count} changes can be completed automatically. Accept automatic changes?":"{count} ᐊᓯᐊᙳᖅᑎᑕᐅᔪᑦ ᐃᖕᒥᓂᒃ ᐱᐊᓂᖕᓂᖅ ᐊᔪᖅᑑᔭᖅᑐᖅ. ᓈᒻᒪᒋᓗᒋᑦ ᐃᖕᒥᓂᒃ ᐊᓯᐊᙳᖅᑐᑦ?"
        ,"JSON definition must be an array":"JSON ᑐᑭᐅᔪᖅ ᐋᖅᕿᒃᓯᒪᔭᕆᐊᖃᖅᑐᖅ"
        ,"JSON definition must be provided":"JSON ᑐᑭᐅᔪᒥᒃ ᑐᓂᓯᔭᕆᐊᓕᒃ"
        ,"JSON library not available":"JSON ᐅᖃᓕᒫᒐᐃᑦ ᒪᓂᒪᙱᑦᑐᑦ"
        ,"JSON.parse() is not available":"JSON.parse() ᒪᓂᒪᙱᑦᑐᖅ"
        ,"Javascript":"ᑎᑎᖅᖃᐅᓯᕆᔾᔪᑎ"
        ,"Javascript Replace":"ᑎᑎᖅᖃᐅᓯᕆᔾᔪᑎ ᐃᓇᖏᖅᑕᐅᔪᖅ"
        ,"Key already in use: ":"ᓇᕿᑦᑕᕆᐊᓕᒃ ᐊᑐᖅᑕᐅᕌᓂᒃᑐᖅ: "
        ,"Label":"ᐊᑎᖅ ᑎᑎᕋᖅᓯᒪᔪᖅ"
        ,"Language":"ᐅᖃᐅᓯᖅ"
        ,"Last Name":"ᐃᓚᒌᑦ ᐊᑎᖓ ᓛᓯᓇᐃᒻᖓ"
        ,"Last updated by":"ᑭᖑᓪᓕᖅᐹᒥᒃ ᓄᑖᙳᖅᑎᖅᑕᐅᓚᐅᖅᑐᖅ ᐅᕗᖓ"
        ,"Layer":"ᖃᓕᕇᖓᓂᖅ"
        ,"Layer Definition":"ᖃᓕᕇᖓᓂᐅᑉ ᑐᑭᖓ"
        ,"Layer Selector":"ᖃᓕᕇᖓᔪᒥᒃ ᓂᕈᐊᖅᓯᔾᔪᑎ"
        ,"Layer Selector Initially Opened":"ᖃᓕᕇᖓᔪᒥᒃ ᓂᕈᐊᖅᓯᔾᔪᑎ ᐅᒃᑯᐃᖅᑕᐅᖅᖃᐅᔪᖅ"
        ,"Layer Selector Suppressed":"ᖃᓕᕇᖓᔪᒥᒃ ᓂᕈᐊᖅᓯᔾᔪᑎ ᓄᖅᖃᖅᑎᑕᐅᔪᖅ"
        ,"Layer name":"ᖃᓕᕇᖓᔫᑉ ᐊᑎᖓ"
        ,"Layers":"ᖃᓕᕇᖓᔪᑦ"
        ,"Less":"ᐲᖅᖢᒍ"
        ,"List Creation Progress":"ᑎᑎᕋᖅᓯᒪᔪᓕᐅᖅᑐᖅ"
        ,"List Refinement Progress":"ᑎᑎᕋᖅᓯᒪᔪᓂᒃ ᐱᐅᓯᒋᐊᖅᓯᓂᖃᖅᑐᖅ"
        ,"List is required on transformation":"ᑎᑎᕋᖅᓯᒪᔪᓂᒃ ᐱᔭᕆᐊᖃᖅᑐᖅ ᐊᓯᐊᙳᖅᑐᒧᑦ"
        ,"Load Info From Database":"ᐃᓕᓗᒋᑦ ᑐᑭᓯᐅᒪᔾᔪᑎᑦ ᓈᓴᐅᑎᓂᒃ/ᑎᑎᖅᖃᓂᒃ ᑐᖅᖁᖅᓯᓯᒪᕝᕕᖕᒥᑦ"
        ,"Load Listing of Media Directory":"ᐃᓕᓗᒋᑦ ᑎᑎᕋᖅᓯᒪᔪᑦ ᖃᕆᑕᐅᔭᒦᑦᑐᑦ ᓇᓃᓐᓂᖏᓐᓄᑦ ᓇᓂᓯᕝᕕᖕᒥᑦ"
        ,"Loading document: ":"ᐃᓕᕙᓪᓕᐊᔪᖅ ᑎᑎᖅᖃᐅᑎ: "
        ,"Loading import profiles":"ᐃᓕᕙᓪᓕᐊᔪᖅ ᐃᓗᐊᓄᐊᖅᑕᐅᔪᑦ ᐱᔾᔪᑎᖃᖅᑐᑦ"
        ,"Loading...":"ᐃᓕᕙᓪᓕᐊᔪᖅ..."
        ,"Location of CSS is undefined for customHtml canvas":"ᐃᓂᖓ CSS ᑐᑭᓕᐅᖅᓯᒪᙱᑦᑐᖅ customHtml canvas-ᒧᑦ"
        ,"Location of CSS is undefined for customSvg canvas":"ᐃᓂᖓ CSS ᑐᑭᓕᐅᖅᓯᒪᙱᑦᑐᖅ customSvg canvas-ᒧᑦ"
        ,"Location of HTML is undefined for customHtml canvas":"ᐃᓂᖓ HTML ᑐᑭᓕᐅᖅᓯᒪᙱᑦᑐᖅ customHtml canvas-ᒧᑦ"
        ,"Location of SVG is undefined for customSvg canvas":"ᐃᓂᖓ SVG ᑐᑭᓕᐅᖅᓯᒪᙱᑦᑐᖅ customSvg canvas-ᒧᑦ"
        ,"Login":"ᑕᐃᑯᙵᕐᓗᓂ"
        ,"Logout":"ᑕᐃᙵᑦ ᐊᓂᓗᓂ"
        ,"Logs":"ᐃᓕᔭᐅᓯᒪᔪᑦ"
        ,"Made with Nunaliit":"ᓄᓇᓖᑦ-ᓂᑦ ᓴᓇᓯᒪᔪᖅ"
        ,"Media":"ᑐᓴᒐᒃᓴᓕᕆᔩᑦ"
        ,"Media Application":"ᖃᕆᑕᐅᔭᒧᑦ ᐃᓚᒋᔭᐅᔪᖅ"
        ,"Media application started":"ᖃᕆᑕᐅᔭᒧᑦ ᐃᓚᒋᔭᐅᔪᖅ ᐱᒋᐊᖅᑐᖅ"
        ,"Media({docId}":"ᖃᕆᑕᐅᔭᒧᑦ ᐃᓚᒋᔭᐅᔪᖅ ({docId}"
        ,"Message":"ᑐᓴᖅᑎᑦᑎᓂᖅ"
        ,"Metadata":"ᑎᑎᖅᖃᐃᑦ ᐊᓯᖏᓐᓂᑦ ᓈᓴᐅᑎᓂᒃ/ᑎᑎᖅᖃᓂᒃ ᐱᖃᖅᑐᑦ"
        ,"Metadata Editor":"ᑎᑎᖅᖃᐃᑦ ᐊᓯᖏᓐᓂᑦ ᓈᓴᐅᑎᓂᒃ/ᑎᑎᖅᖃᓂᒃ ᐱᖃᖅᑐᓂᒃ ᐋᖅᕿᒃᓱᐃᔨ"
        ,"Missing input. Can not proceed.":"ᐱᑕᖃᙱᑦᑐᖅ ᐃᓕᔭᐅᔪᒥᑦ. ᑲᔪᓯᓂᖅ ᐊᔪᖅᑐᖅ."
        ,"Model Browser":"ᐋᖅᕿᐅᒪᔪᖅ ᕿᓂᕈᑎ"
        ,"Models":"ᐋᖅᕿᐅᒪᔪᑦ"
        ,"Modify Document":"ᐋᖅᕿᒋᐊᕐᓗᒍ ᑎᑎᖅᖃᖅ"
        ,"Modify existing document":"ᐋᖅᕿᒋᐊᕐᓗᒍ ᑕᐃᒪᐅᔪᖅ ᑎᑎᖅᖃᖅ"
        ,"Module":"ᐃᓕᓐᓂᐊᕈᑎ"
        ,"More":"ᐊᖏᓂᖅᓴᖅ"
        ,"More Details":"ᓇᓗᓇᐃᔭᖅᓯᒪᔪᑦ"
        ,"More Info":"ᑐᑭᓯᐅᒪᔾᔪᑎᒃᑲᓐᓂᕐᓂᒃ ᐱᓂᐊᕐᓗᑎᑦ"
        ,"More lines... ({num})":"ᑎᑯᓕᐊᖅᓯᒪᒃᑲᓐᓂᖅᑐᑦ... ({num})"
        ,"More than one import entries report identifier: {id}":"ᐊᑕᐅᓯᐅᖏᑦᑐᒥᒃ ᐃᓕᔭᐅᔪᓂᒃ ᐃᓕᓯᓂᕐᓄᑦ ᐅᓂᑉᑳᓂᒃ ᓇᓗᓇᐃᖅᓯᔾᔪᑎ: {id}"
        ,"Must enter a document identifier":"ᐃᓕᓯᔭᕆᐊᓕᒃ ᑎᑎᖅᖃᒧᑦ ᓇᓗᓇᐃᖅᓯᔾᔪᑎᒥᒃ"
        ,"Must enter a layer name":"ᐃᓕᓯᔭᕆᐊᓕᒃ ᖃᓕᕆᔭᐅᔫᑉ ᐊᑎᖓᓂᒃ"
        ,"Must enter a schema name":"ᐃᓕᓯᔭᕆᐊᓕᒃ ᐋᖅᕿᒃᓯᒪᔫᑉ ᐊᑎᖓ"
        ,"Must select a view":"ᓂᕈᐊᕆᐊᖃᖅᑐᖅ ᑕᑯᒃᓴᐅᓂᐊᖅᑐᒥᒃ"
        ,"Must select an import profile":"ᓂᕈᐊᕆᐊᖃᖅᑐᖅ ᐃᓕᔭᐅᔪᖅ ᐱᔾᔪᑕᐅᔪᒥᒃ"
        ,"My User":"ᐅᕙᒻᓄᑦ ᐊᑐᖅᑎᐅᓂᒻᓄᑦ"
        ,"Name":"ᐊᑎᐊ"
        ,"Name of new list":"ᐊᑎᖓ ᓄᑖᑉ ᑎᑎᕋᖅᓯᒪᔪᑦ"
        ,"Navigation":"ᓇᒧᙵᐅᓂᖅ"
        ,"New File":"ᓄᑖᖅ ᑎᑎᖅᖃᖅ"
        ,"Next":"ᑐᒡᓕᐊ"
        ,"No":"ᐋᒃᑲ"
        ,"No Document":"ᑎᑎᖅᖃᐅᑎᑕᖃᙱᑦᑐᖅ"
        ,"No changes detected in the import data":"ᐊᓯᐊᙳᖅᑐᓂᒃ ᖃᐅᔨᓐᓇᙱᑦᑐᖅ ᐃᓕᔭᐅᔪᓂᒃ ᓈᓴᐅᑎᓂᑦ/ᑎᑎᖅᖃᓂᑦ"
        ,"No document found":"ᑎᑎᖅᖃᒥᒃ ᓇᓂᓯᙱᑦᑐᖅ"
        ,"No document modified.":"ᑎᑎᖅᖃᒥᒃ ᐋᖅᕿᒋᐊᖅᓯᓂᖅᑕᖃᙱᑦᑐᖅ"
        ,"No list Selected":"ᑎᑎᕋᖅᓯᒪᔪᒥᒃ ᓂᕈᐊᖅᓯᒪᙱᑦᑐᖅ"
        ,"No media found on {docId}":"ᖃᕆᑕᐅᔭᒧᑦ ᐃᓚᒋᔭᐅᔪᒥᒃ ᓇᓂᓯᙱᑦᑐᖅ ᐅᕙᓂ {docId}"
        ,"No results returned by search":"ᖃᓄᐃᖓᓂᐅᔪᓂᒃ ᐅᑎᖅᑐᖃᙱᑦᑐᖅ ᕿᓂᖅᓴᐃᓂᕐᒥᑦ"
        ,"No submission available":"ᑐᓂᓯᓂᕐᒥᒃ ᒪᓂᒪᔪᖃᙱᑦᑐᖅ"
        ,"Number of documents: {count}":"ᖃᑉᓯᐅᓂᖏᑦ ᑎᑎᖅᖃᐃᑦ: {count}"
        ,"Nunaliit Atlas":"ᓄᓇᓖᑦ-ᒧᑦ ᓄᓇᙳᐊᖅ"
        ,"Nunaliit Graph":"ᓄᓇᓖᑦ-ᒧᑦ ᑎᑎᕋᐅᔭᖅᓯᒪᔪᖅ"
        ,"OK":"ᓈᒻᒪᒃᑐᖅ"
        ,"Ongoing time interval must begin before now":"ᓄᖅᖃᖅᑕᐃᓐᓇᕐᓂᖅ ᐱᒋᕆᐊᖃᖅᑐᖅ ᓯᕗᓂᐊᒍᑦ ᒫᓐᓇᐅᔫᑉ"
        ,"Only LineString Geometries":"ᑎᑯᓕᐊᖅᓯᒪᔪᓄᑎᐃᓐᓇᖅ ᓈᓴᐅᓯᕆᔾᔪᑏᑦ"
        ,"Only Point Geometries":"ᐃᓕᓯᒪᔪᒧᑐᐃᓐᓇᖅ ᓈᓴᐅᓯᕆᔾᔪᑏᑦ"
        ,"Only Polygon Geometries":"ᓇᓗᓇᐃᒃᑯᑕᑐᐃᓐᓇᓄᑦ ᓈᓴᐅᓯᕆᔾᔪᑏᑦ"
        ,"Operation cancelled by user":"ᐊᐅᓛᖅᑎᑦᑎᓂᖅ ᓄᖅᖃᖅᑎᑕᐅᔪᖅ ᐊᑐᖅᑎᒧᑦ"
        ,"Operation not recognized":"ᐊᐅᓛᖅᑎᑦᑎᓂᖅ ᐃᓕᑕᕆᔭᐅᖏᑦᑐᖅ"
        ,"Operation {index} of {count}":"ᐊᐅᓛᖅᑎᑦᑎᓂᖅ {index} {count}"
        ,"Order":"ᐋᖅᕿᐅᒪᓂᖓ"
        ,"Original":"ᐱᒋᔭᐅᖅᑲᐅᑕᐅᓚᐅᖅᑐᖅ"
        ,"Original Id":"ᓇᓗᓇᐃᖅᓯᔾᔪᑎᐅᖅᖃᐅᑕᐅᓚᐅᖅᑐᖅ"
        ,"Original String":"ᐋᖅᕿᒃᓯᒪᔪᑦ ᓈᓴᐅᑏᑦ/ᑎᑎᖅᖃᐅᑕᐅᖅᖃᐅᑕᐅᔪᖅ"
        ,"Overlays":"ᖃᓪᓖᑦ"
        ,"Password":"ᑕᐃᑯᙵᕈᖕᓇᕈᑏᑦ"
        ,"Password Recovery":"ᑕᐃᑯᙵᕈᑎᒥᒃ ᐅᑎᖅᑎᑦᑎᓂᖅ"
        ,"Password Recovery Failure":"ᑕᐃᑯᙵᕈᑎᒥᒃ ᐅᑎᖅᑎᑦᑎᓂᖅ ᐊᔪᖅᑐᖅ"
        ,"Password Recovery Initiated":"ᑕᐃᑯᙵᕈᑎᒥᒃ ᐅᑎᖅᑎᑦᑎᓂᖅ ᐱᒋᐊᖅᑐᖅ"
        ,"Password is too short":"ᑕᐃᑯᙵᕈᑎ ᓇᐃᓗᐊᖅᑐᖅ"
        ,"Password recovery initiated. Check for an e-mail to complete password recovery":"ᑕᐃᑯᙵᕈᑎᒥᒃ ᐅᑎᖅᑎᑦᑎᓂᖅ ᐱᒋᐊᖅᑐᖅ. ᖃᐅᔨᒋᐊᕐᓗᒍ ᖃᕆᑕᐅᔭᒃᑯᑦ ᑎᑎᖅᖃᐃᑦ ᐱᐊᓂᖕᓂᐊᕐᓗᒍ ᑕᐃᑯᙵᕈᑎᒥᒃ ᐅᑎᖅᑎᑦᑎᓂᖅ"
        ,"Password should have at least 6 characters":"ᑕᐃᑯᙵᕈᑎ 6-ᖑᔭᕆᐊᓖᑦ "
        ,"Password was recovered successfully.":"ᑕᐃᑯᙵᕈᑎ ᐅᑎᖅᑎᑦᑎᓂᖅ ᐱᐊᓂᑦᑎᐊᖅᑐᖅ."
        ,"Passwords do not match":"ᑕᐃᑯᙵᕈᖕᓇᐅᑏᑦ ᐊᔾᔨᒌᙱᑦᑐᑦ"
        ,"Perform Analysis":"ᖃᐅᔨᓴᐃᓗᓂ"
        ,"Please login":"ᑕᐃᑯᙵᕐᓗᑎᑦ"
        ,"Please":"ᐊᑏ"
        ,"Preparing Report":"ᐱᓕᕆᐊᖑᕙᓪᓕᐊᔪᖅ ᐅᓂᑉᑳᖅ"
        ,"Previous":"ᓯᕗᓂᐊᓃᑦᑐᖅ"
        ,"Preview":"ᑕᐅᑦᑐᖓ"
        ,"Problem obtaining documents from import profile":"ᐊᔪᖅᑐᖅ ᐱᓂᐊᕐᓗᓂ ᑎᑎᖅᖃᓂᒃ ᐃᓕᓗᒍ ᐱᔾᔪᑎᖃᖅᑐᒥᑦ "
        ,"Problem obtaining documents from layer":"ᐊᔪᖅᑐᖅ ᐱᓂᐊᕐᓗᓂ ᑎᑎᖅᖃᓂᒃ ᖃᓕᐅᔪᒥᑦ"
        ,"Problem obtaining documents from schema":"ᐊᔪᖅᑐᖅ ᐱᓂᐊᕐᓗᓂ ᑎᑎᖅᖃᓂᒃ ᐋᖅᕿᒃᓯᒪᔪᒥᑦ"
        ,"Problem obtaining documents from view":"ᐊᔪᖅᑐᖅ ᐱᓂᐊᕐᓗᓂ ᑎᑎᖅᖃᓂᒃ ᑕᑯᒃᓴᐅᔪᒥᑦ"
        ,"Problem obtaining documents with media files in analyzed state":"ᐊᔪᖅᑐᖅ ᐱᓂᐊᕐᓗᓂ ᑎᑎᖅᖃᓂᒃ ᐱᖃᖅᑐᓂᒃ ᖃᕆᑕᐅᔭᒧᑦ ᐃᓚᒋᔭᐅᔪᓄᑦ ᑎᑎᖅᖃᓂᒃ ᖃᐅᔨᓴᐃᓂᕐᒦᑎᓪᓗᒍ"
        ,"Problem obtaining documents with media files in approved state":"ᐊᔪᖅᑐᖅ ᐱᓂᐊᕐᓗᓂ ᑎᑎᖅᖃᓂᒃ ᐱᖃᖅᑐᓂᒃ ᖃᕆᑕᐅᔭᒧᑦ ᐃᓚᒋᔭᐅᔪᓄᑦ ᑎᑎᖅᖃᓂᒃ ᓈᒻᒪᒋᔭᐅᑎᓪᓗᒍ"
        ,"Problem obtaining documents with media files in attached state":"ᐊᔪᖅᑐᖅ ᐱᓂᐊᕐᓗᓂ ᑎᑎᖅᖃᓂᒃ ᐱᖃᖅᑐᓂᒃ ᖃᕆᑕᐅᔭᒧᑦ ᐃᓚᒋᔭᐅᔪᓄᑦ ᑎᑎᖅᖃᓂᒃ ᐃᓚᐅᑎᑦᑎᑎᓪᓗᒍ"
        ,"Problem obtaining documents with media files in submitted state":"ᐊᔪᖅᑐᖅ ᐱᓂᐊᕐᓗᓂ ᑎᑎᖅᖃᓂᒃ ᐱᖃᖅᑐᓂᒃ ᖃᕆᑕᐅᔭᒧᑦ ᐃᓚᒋᔭᐅᔪᓄᑦ ᑎᑎᖅᖃᓂᒃ ᑐᓂᓯᑎᓪᓗᒍ"
        ,"Problem obtaining documents with media files in waiting state":"ᐊᔪᖅᑐᖅ ᐱᓂᐊᕐᓗᓂ ᑎᑎᖅᖃᓂᒃ ᐱᖃᖅᑐᓂᒃ ᖃᕆᑕᐅᔭᒧᑦ ᐃᓚᒋᔭᐅᔪᓄᑦ ᑎᑎᖅᖃᓂᒃ ᐅᑕᖅᕿᑎᓪᓗᒍ"
        ,"Problem obtaining skeleton documents":"ᐊᔪᖅᑐᖅ ᑎᑎᖅᖃᓂᒃ ᐱᓂᐊᕐᓗᓂ"
        ,"Proceed":"ᑲᔪᓯᓗᓂ"
        ,"Proceed with Import Operations":"ᑲᔪᓯᓗᓂ ᐃᓕᔭᐅᔪᓂᒃ ᐊᐅᓛᖅᑎᑦᑎᓂᖃᕐᓗᓂ"
        ,"Process completed.":"ᐱᐊᓂᒃᑐᖅ."
        ,"Progress":"ᐱᕙᓪᓕᐊᔪᖅ"
        ,"Queries":"ᐊᐱᖅᖁᑏᑦ"
        ,"Query Users":"ᐊᐱᖅᖁᑎᒧᑦ ᐊᑐᖅᑏᑦ"
        ,"Range":"ᐃᓂᒋᔭᐅᔪᖅ"
        ,"Re-Submit Geometries":"ᑐᓂᒃᑲᓐᓂᕐᓗᒋᑦ ᓈᓴᐅᓯᕆᔾᔪᑏᑦ"
        ,"Re-Submit Media":"ᑐᓂᐅᑎᒋᒃᑲᓐᓂᕐᓗᒍ ᖃᕆᑕᐅᔭᒧᑦ ᐃᓚᒋᔭᐅᔪᖅ"
        ,"Record":"ᑎᑎᕋᐅᓯᕆᓗᒍ"
        ,"Recover Password":"ᐅᑎᖅᑎᓪᓗᒍ ᑕᐃᑯᙵᕈᖕᓇᐅᑎ"
        ,"Recovering password for a user associated with the e-mail address: {address}":"ᐅᑎᖅᑎᑦᑎᓂᖅ ᑕᐃᑯᙵᕈᖕᓇᐅᑎᒥᑦ ᐊᑐᖅᑎᐅᔪᒧᑦ ᐱᔾᔪᑎᖃᖅᑐᖅ ᖃᕆᑕᐅᔭᒃᑯᑦ ᑎᑎᖅᖃᓄᑦ ᑐᕌᕈᑎᒧᑦ: {address}"
        ,"Reference":"ᐱᔾᔪᑕᐅᔪᖅ"
        ,"Reference:":"ᐱᔾᔪᑕᐅᔪᖅ:"
        ,"References":"ᖃᐅᔨᒋᐊᕐᕕᐅᔪᖕᓇᖅᑐᑦ"
        ,"Refine List":"ᐱᐅᓯᒋᐊᕐᓗᒋᑦ ᑎᑎᕋᖅᓯᒪᔪᑦ"
        ,"Refresh":"ᓄᑖᙳᖅᑎᕐᓗᒍ"
        ,"Regex Expression":"ᐊᔾᔨᖏᓐᓂᒃ ᑎᑎᖅᖃᖃᖅᑐᑦ ᖃᐅᔨᑎᑦᑎᓂᖅ"
        ,"Regex Search":"ᐊᔾᔨᖏᓐᓂᒃ ᑎᑎᖅᖃᖃᖅᑐᓂᒃ ᕿᓂᖅᓴᐃᓂᖅ"
        ,"Registration Initiated":"ᐊᑎᓕᐅᕆᓂᖅ ᐱᒋᐊᖅᑎᑕᐅᔪᖅ"
        ,"Reject":"ᕿᐱᓗᒃᑕᐅᔪᖅ"
        ,"Relation: ":"ᐱᔾᔪᑎᖓ: "
        ,"Remind me later":"ᐃᖅᖃᐃᑎᓐᓂᐊᖅᐸᖕᒪ ᐅᐊᑦᑎᐊᕈ"
        ,"Remove":"ᐲᕐᓗᒍ"
        ,"Replace Text":"ᐃᓇᖏᕐᓗᒍ ᑎᑎᕋᖅᓯᒪᔪᖅ"
        ,"Reply":"ᑭᐅᓗᓂ:"
        ,"Report":"ᐅᓂᑉᑳᖅ"
        ,"Required fields missing for ":"ᐱᔭᕆᐊᖃᖅᑐᑦ ᐃᓪᓕᕆᕝᕕᐅᓗᑎᒃ ᐱᑕᖃᙱᑦᑐᖅ ᐅᕗᖓ "
        ,"Reset":"ᐊᓯᐊᙳᕐᓗᒍ"
        ,"Reset Password":"ᐊᓯᐊᙳᕐᓗᒍ ᑕᐃᑯᙵᕈᖕᓇᐅᑎ"
        ,"Reset password?":"ᐊᓯᐊᙳᕐᓗᒍ ᑕᐃᑯᙵᕈᖕᓇᐅᑎ?"
        ,"Resolution":"ᐱᖁᔨᕗᖔᒧᑦ ᓈᓴᐅᑎ"
        ,"Revision":"ᐋᖅᕿᒋᐊᖅᓯᓂᖅ"
        ,"Roles":"ᐱᓕᕆᐊᑦ"
        ,"Root Schema":"ᐱᒋᐊᕐᕕᖓ ᐋᖅᕿᒃᓯᒪᔫᑉ"
        ,"STOPPING: Failed verifying view ":"ᓄᖅᖃᕐᓂᐊᖅᑐᖅ: ᐊᔪᖅᑐᖅ ᓇᓗᓇᐃᖅᓯᓂᖅ ᑕᑯᒃᓴᐅᔪᒥᑦ "
        ,"Save":"ᐊᓯᐅᔨᑦᑕᐃᓕᓗᒍ"
        ,"Schema":"ᐋᖅᕿᒃᓯᒪᔪᖅ"
        ,"Schema Display":"ᐋᖅᕿᒃᓯᒪᔪᖅ ᑕᑯᒃᓴᐅᔪᖅ"
        ,"Schemas":"ᐋᖅᕿᒃᓯᒪᔪᑦ"
        ,"Script":"ᑎᑎᕋᖅᓯᒪᔪᖅ"
        ,"Script(":"ᑎᑎᕋᖅᓯᒪᔪᖅ("
        ,"Script:":"ᑎᑎᕋᖅᓯᒪᔪᖅ:"
        ,"Scroll Map":"ᓄᓇᙳᐊᒥᑦ ᑕᐅᓄᙵᐅᓗᓂ"
        ,"Search":"ᕿᓂᖅᓴᕐᓗᓂ"
        ,"Search Terms":"ᕿᓂᕐᓗᒋᑦ ᑐᑭᐅᔪᑦ"
        ,"Search result is empty":"ᕿᓂᕐᓗᒋᑦ ᖃᓄᐃᖓᓂᕐᒥᑦ ᐃᓗᓕᖃᙱᑦᑐᖅ"
        ,"Search results empty":"ᕿᓂᕐᓗᒋᑦ ᖃᓄᐃᖓᓂᐅᔪᓂᒃ ᐃᓗᓕᖃᙱᑦᑐᖅ"
        ,"Search term":"ᕿᓂᕐᓗᒋᑦ ᑐᑭᐅᔪᖅ"
        ,"Search terms":"ᕿᓂᕐᓗᒋᑦ ᑐᑭᐅᔪᑦ"
        ,"Search:":"ᕿᓂᖅᓴᕐᓗᓂ:"
        ,"Select":"ᓂᕈᐊᕐᓗᒍ"
        ,"Select Document":"ᓂᕈᐊᕐᓗᒍ ᑎᑎᖅᖃᖅ"
        ,"Select Document Schema":"ᓂᕈᐊᕐᓗᒍ ᑎᑎᖅᖃᖅ ᐋᖅᕿᒃᓯᒪᔪᖅ"
        ,"Select Document Transform":"ᓂᕈᐊᕐᓗᒍ ᑎᑎᖅᖃᖅ ᐊᓯᐊᙳᕐᓗᒍ"
        ,"Select Language":"ᓂᕈᐊᕐᓗᒍ ᐅᖃᐅᓯᖅ"
        ,"Select Layers":"ᓂᕈᐊᕐᓗᒍ ᖃᓕᕇᑦ"
        ,"Select Roles":"ᓂᕈᐊᕐᓗᒍ ᐱᓕᕆᐊᑦ"
        ,"Select Search Filter":"ᓂᕈᐊᕐᓗᒍ ᕿᓂᖅᓴᐃᓂᕐᒧᑦ ᓇᓗᓇᐃᒃᑯᑦᑎᖅᓯᒪᔪᑦ"
        ,"Select a media":"ᓂᕈᐊᕐᓗᒍ ᖃᕆᑕᐅᔭᒧᑦ ᐃᓚᒋᔭᐅᔪᖅ"
        ,"Select a schema":"ᓂᕈᐊᕐᓗᒍ ᐋᖅᕿᒃᓯᒪᔪᖅ"
        ,"Select a schema:":"ᓂᕈᐊᕐᓗᒍ ᐋᖅᕿᒃᓯᒪᔪᖅ:"
        ,"Select application started":"ᓂᕈᐊᕐᓗᒍ ᐊᑐᖅᑐᖅ ᐱᒋᐊᖅᑐᖅ"
        ,"Select documents from a layer":"ᓂᕈᐊᕐᓗᒍ ᑎᑎᖅᖃᐃᑦ ᖃᓕᕇᒥᑦ"
        ,"Select documents from a schema type":"ᓂᕈᐊᕐᓗᒍ ᑎᑎᖅᖃᐃᑦ ᖃᓄᐃᑦᑑᓂᖓᑕ ᐋᖅᕿᒃᓯᒪᔪᒥᑦ"
        ,"Select documents from an import profile":"ᓂᕈᐊᕐᓗᒍ ᑎᑎᖅᖃᐃᑦ ᐱᔪᑦ ᐃᓕᓗᒍ ᐱᔾᔪᑎᖃᖅᑐᒥᑦ"
        ,"Select documents reported in a view":"ᓂᕈᐊᕐᓗᒍ ᑎᑎᖅᖃᐃᑦ ᐅᖃᐅᓯᐅᔪᑦ ᑕᑯᒃᓴᐅᔪᒥᑦ"
        ,"Select documents that are not reachable by reference":"ᓂᕈᐊᕐᓗᒍ ᑎᑎᖅᖃᐃᑦ ᑎᑭᑕᒃᓴᐅᖏᑦᑐᑦ ᐱᔾᔪᑕᐅᔪᒃᑯᑦ"
        ,"Select documents that have an invalid source":"ᓂᕈᐊᕐᓗᒍ ᑎᑎᖅᖃᐃᑦ ᓈᒻᒪᙱᑦᑐᒥᒃ ᐱᕝᕕᐅᔪᖃᖅᑐᑦ"
        ,"Select documents that have broken references":"ᓂᕈᐊᕐᓗᒍ ᑎᑎᖅᖃᐃᑦ ᓯᖁᒥᓯᒪᔪᒥᒃ ᐱᔾᔪᑕᐅᔪᖃᖅᑐᑦ"
        ,"Select documents that reference another one":"ᓂᕈᐊᕐᓗᒍ ᑎᑎᖅᖃᐃᑦ ᐱᔾᔪᑕᐅᔪᒥᒃ ᐊᓯᐊᓂᒃ ᐱᑕᖃᖅᑐᖅ"
        ,"Select documents with analyzed media files":"ᓂᕈᐊᕐᓗᒍ ᑎᑎᖅᖃᐃᑦ ᖃᐅᔨᓴᖅᑕᐅᓯᒪᔪᓂᒃ ᖃᕆᑕᐅᔭᒧᑦ ᐃᓚᒋᔭᐅᔪᖃᖅᑐᑦ"
        ,"Select documents with approved media files":"ᓂᕈᐊᕐᓗᒍ ᑎᑎᖅᖃᐃᑦ ᓈᒻᒪᒋᔭᐅᔪᒥᒃ ᖃᕆᑕᐅᔭᒧᑦ ᐃᓚᒋᔭᐅᔪᖃᖅᑐᑦ"
        ,"Select documents with attached media files":"ᓂᕈᐊᕐᓗᒍ ᑎᑎᖅᖃᐃᑦ ᐃᓚᐅᔪᒥᒃ ᖃᕆᑕᐅᔭᒧᑦ ᐃᓚᒋᔭᐅᔪᖃᖅᑐᑦ"
        ,"Select documents with submitted media files":"ᓂᕈᐊᕐᓗᒍ ᑎᑎᖅᖃᐃᑦ ᑐᓂᔭᐅᔪᒥᒃ ᖃᕆᑕᐅᔭᒧᑦ ᐃᓚᒋᔭᐅᔪᖃᖅᑐᑦ"
        ,"Select documents with waiting media files":"ᓂᕈᐊᕐᓗᒍ ᑎᑎᖅᖃᐃᑦ ᐅᑕᖅᕿᔪᓂᒃ ᖃᕆᑕᐅᔭᒧᑦ ᐃᓚᒋᔭᐅᔪᖃᖅᑐᑦ"
        ,"Select from Javascript":"ᓂᕈᐊᕐᓗᒍ ᑎᑎᖅᖃᐅᓯᕆᔾᔪᑎ"
        ,"Select geometries from a layer":"ᓂᕈᐊᕐᓗᒍ ᓈᓴᐅᓯᕆᔾᔪᑏᑦ ᖃᓕᕇᖓᔪᒥᑦ"
        ,"Select invalid documents":"ᓂᕈᐊᕐᓗᒍ ᓈᒻᒪᙱᑦᑐᑦ ᑎᑎᖅᖃᐃᑦ"
        ,"Select schema":"ᓂᕈᐊᕐᓗᒍ ᖃᓄᐃᑦᑑᓂᖓᑕ ᐋᖅᕿᒃᓯᒪᔪᖅ"
        ,"Select skeleton documents":"ᓂᕈᐊᕐᓗᒍ ᐋᖅᕿᒃᓯᒫᓂᒃᑐᑦ ᑎᑎᖅᖃᐃᑦ"
        ,"Send":"ᐊᐅᓪᓚᖅᑎᓪᓗᒍ"
        ,"Send e-mail to submitter with reason for rejection":"ᐊᐅᓪᓚᖅᑎᓪᓗᒍ ᖃᕆᑕᐅᔭᒃᑯᑦ ᑎᑎᖅᖃᑎᒍᑦ ᐊᐅᓪᓚᖅᑎᑦᑎᔪᒧᑦ ᕿᐱᓗᒃᑕᐅᓂᖓ ᐅᖃᐅᓯᕆᓗᒍ"
        ,"Send mail to {name}":"ᐊᐅᓪᓚᖅᑎᓪᓗᒍ ᑎᑎᖅᖃᑎᒍᑦ ᐅᕗᖓ {name}"
        ,"Send us information":"ᐊᐅᓪᓚᖅᑎᑦᑎᕝᕕᒋᓗᑕ ᑐᑭᓯᐅᒪᔾᔪᑎᓂᒃ"
        ,"Server must be specified for CouchDb AuthService":"ᐱᔨᑦᑎᕋᐃᔾᔪᑎ ᐅᖃᖅᑕᐅᓯᒪᔭᕆᐊᖃᖅᑐᖅ ᐅᕗᖓ CouchDb AuthService"
        ,"Set Password":"ᐋᖅᕿᒡᓗᒍ ᑕᐃᑯᙵᕈᖕᓇᐅᑎ"
        ,"Show":"ᑕᑯᒃᓴᐅᑎᑦᑎᓗᑎᑦ"
        ,"Show my password":"ᑕᑯᒃᓴᐅᑎᓪᓗᒍ ᑕᐃᑯᙵᕈᖕᓇᐅᑎᒐ"
        ,"Skeleton documents":"ᐋᖅᕿᒃᓯᒫᓂᒃᑐᑦ ᑎᑎᖅᖃᐃᑦ"
        ,"Sticky Nodes":"Sticky Nodes"
        ,"Stop":"ᓄᖅᑲᕆᑦ"
        ,"Subject":"ᐱᔾᔪᑎᖓ"
        ,"Submission Id":"ᑐᓂᓯᓂᕐᒧᑦ ᓇᓗᓇᐃᖅᓯᔾᔪᑎ"
        ,"Submission State":"ᑐᓂᓯᓂᕐᒧᑦ ᖃᓄᐃᖓᓂᖓ"
        ,"Submission Type":"ᑐᓂᓯᓂᕐᒧᑦ ᖃᓄᐃᑦᑑᓂᖓ"
        ,"Submission approved":"ᑐᓂᓯᓂᖅ ᓈᒻᒪᒋᔭᐅᔪᖅ"
        ,"Submission denied":"ᑐᓂᓯᓂᖅ ᕿᐱᓗᒃᑕᐅᔪᖅ"
        ,"Submissions to the database will not appear until they are approved":"ᑐᓂᓯᓃᑦ ᓈᓴᐅᑎᓄᑦ/ᑎᑎᖅᖃᓄᑦ ᑐᖅᖁᖅᓯᓯᒪᕝᕕᖕᒧᑦ ᑕᑯᒃᓴᐅᔾᔮᙱᑦᑐᑦ ᑭᓯᐊᓂ ᓈᒻᒪᒋᔭᐅᕌᓂᒃᐸᑕ"
        ,"Submitter":"ᑐᓂᓯᔪᖅ"
        ,"Tangibles Application":"ᐊᑐᖅᑕᐅᔪᑦ ᑐᒃᓯᕋᐅᓯᐅᕈᑏ"
        ,"Tangibles application started":"ᑕᑯᒃᓴᐅᔪᑦ ᑐᒃᓯᕋᐅᓯᐅᕈᑎ ᐱᒋᐊᖅᑎᑕᐅᔪᖅ"
        ,"Temporary View":"ᐊᑐᖅᑕᐅᓚᐅᐱᓪᓚᒃᑐᖅ ᑕᑯᒃᓴᐅᔪᖅ"
        ,"Test Temporary View":"ᐆᒃᑐᕋᖅᑕᐅᔪᖅ ᐊᑐᖅᑕᐅᓚᐅᐱᓪᓚᒃᑐᖅ ᑕᑯᒃᓴᐅᔪᖅ"
        ,"Text":"ᑎᑎᖅᖃᖅ"
        ,"Text Replace":"ᑎᑎᕋᖅᓯᒪᔪᖅ ᐃᓇᖏᖅᑕᐅᔪᖕᓇᖅᑐᖅ"
        ,"Text Search":"ᑎᑎᕋᖅᓯᒪᔪᒥᒃ ᕿᓂᖅᓴᐃᓂᖅ"
        ,"The information is expired.":"ᑐᑭᓯᐅᒪᔾᔪᑎ ᐃᓱᓕᑦᑐᖅ."
        ,"The mail subject":"ᑎᑎᖅᖃᒧᑦ ᐱᔾᔪᑕᐅᔪᖅ"
        ,"The projection {srsName} is not supported. Atlas may no function properly.":"ᑕᑯᒃᓴᐅᔪᖅ {srsName} ᐃᑲᔪᖅᑕᐅᖏᑦᑐᖅ. ᓄᓇᙳᐊᖅ ᐊᔪᕐᓂᐊᖅᑐᒃᓴᐅᔪᖅ."
        ,"The provided passwords must match":"ᑕᐃᑯᙵᕈᖕᓇᐅᑏᑦ ᐊᔾᔨᒌᒋᐊᖃᖅᑐᑦ"
        ,"The two passwords should match":"ᒪᕐᕉᒃ ᑕᐃᑯᙵᕈᖕᓇᐅᑏᑦ ᐊᔾᔨᒌᒋᐊᓖᒃ"
        ,"There was a problem saving your answers. You will be prompted again next time you log in.":"ᐊᔪᖅᖃᐅᔪᖅ ᐊᓯᐅᔨᑦᑕᐃᓕᓂᐊᕐᓗᒋᑦ ᑭᐅᔭᑎᑦ. ᖃᐅᔨᑎᑕᐅᒃᑲᓐᓂᕐᓂᐊᖅᑐᑎᑦ ᑭᖑᓪᓕᕐᒥᑦ ᑕᐃᑯᙵᕆᐊᕈᕕᑦ."
        ,"This appears to be the first time that you are importing this profile. Accept all?":"ᓯᕗᓪᓕᖅᐹᕆᔫᔭᖅᑕᐃᑦ ᐃᓕᓯᓂᕐᒧᑦ ᐱᔾᔪᑕᐅᔪᒥᒃ. ᓈᒻᒪᒋᓗᒃᑖᕐᓗᒋᑦ?"
        ,"This cluster contains {count} features":"ᑲᑎᓯᒪᔪᖅ ᐃᓗᓕᖃᖅᑐᖅ {count} ᐃᓚᒋᔭᐅᔪᓂᒃ"
        ,"This feature is a cluster and can not be edited directly. Please":"ᐃᓚᒋᔭᐅᔪᖅ ᑲᑎᓯᒪᔫᔪᖅ ᐊᒻᒪᓗ ᐋᖅᕿᒃᓱᕐᓂᖅ ᑕᐃᑯᖓ ᐊᔪᖅᑐᖅ. ᐊᑏ"
        ,"This object is being modified. Do you wish to continue and revert current changes?":"ᐱᖁᑎ ᐋᖅᕿᒃᓱᖅᑕᐅᔪᖅ. ᑲᔪᓯᔪᒪᕕᑦ ᐊᒻᒪᓗ ᐅᑎᖅᑎᓪᓗᒋᑦ ᐊᓯᐊᙳᖅᑎᖅᖃᐅᔪᑦ?"
        ,"This page must be called from a link received in an e-mail":"ᒪᒃᐱᖅᑐᒐᖅ ᐱᔭᐅᔭᕆᐊᓕᒃ ᑕᐃᑯᙵᕈᖕᓇᐅᑎᒥᒃ ᖃᕆᑕᐅᔭᒃᑯᑦ ᑎᑎᖅᖃᑎᒍᑦ ᐊᐅᓚᖅᑎᑕᐅᓚᐅᖅᑐᒥᑦ"
        ,"Title":"ᑕᐃᒎᓯᐊ"
        ,"To":"ᐅᕗᖓ"
        ,"Transform":"ᐊᓯᐊᙳᕐᓗᓂ"
        ,"Transform Progress":"ᐊᓯᐊᙳᖅᐸᓪᓕᐊᔪᖅ"
        ,"Transformations completed with some failures":"ᐊᓯᐊᙳᖅᑎᕆᓃᑦ ᐱᐊᓂᒃᑐᑦ ᐃᓚᖏᑦ ᐊᔪᖅᖢᑎᒃ"
        ,"Transformations completed. Successful: {ok} Failures: {fail} Skipped: {skipped}":"ᐊᓯᐊᙳᖅᑎᕆᓃᑦ ᐱᐊᓂᒃᑐᑦ. ᐱᐊᓂᑦᑎᐊᖅᑐᖅ: {ok} ᐊᔪᖅᑐᑦ: {fail} ᖄᖏᖅᑕᐅᔪᖅ: {skipped}"
        ,"Translation":"ᐃᓄᒃᑎᑑᓕᕆᓂᖅ"
        ,"Tree Display":"ᓇᐹᖅᑐᖅ ᑕᑯᒃᓴᐅᓂᖓ"
        ,"Tree View":"ᓇᐹᖅᑐᖅ ᑕᑯᒃᓴᐅᑉᓗᓂ"
        ,"Type":"ᑭᓲᓂᖓ"
        ,"Type of refinement":"ᖃᓄᐃᑦᑑᓂᖓ ᐋᖅᕿᒋᐊᖅᓯᓂᖅ"
        ,"Unable to access help document: {docId}":"ᐊᔪᖅᑐᖅ ᐃᑲᔪᖅᑐᖅ ᑎᑎᖅᖃᒧᐊᕐᓂᖅ: {docId}"
        ,"Unable to complete operation : {err}":"ᐱᐊᓂᖕᓂᖅ ᐊᔪᖅᑐᖅ ᐊᐅᓛᖅᑎᑦᑎᓂᖅ: {err}"
        ,"Unable to complete operation because the user information has been updated.":"ᐱᐊᓂᖕᓂᖅ ᐊᔪᖅᑐᖅ ᐊᐅᓛᖅᑎᑦᑎᓂᖅ ᐊᑐᖅᑎᒧᑦ ᑐᑭᓯᐅᒪᔾᔪᑏᑦ ᓄᑖᙳᖅᑎᑕᐅᓚᐅᕐᒪᑕ."
        ,"Unable to create a new list":"ᓴᖅᕿᑦᑎᓂᖅ ᓄᑖᒥᒃ ᑎᑎᕋᖅᓯᒪᔪᓂᒃ ᐊᔪᖅᑐᖅ"
        ,"Unable to create document. Are you logged in?":"ᓴᖅᕿᑦᑎᓂᖅ ᑎᑎᖅᖃᒥᒃ ᐊᔪᖅᑐᖅ. ᑕᐃᑯᙵᖅᓯᒪᕕᑦ?"
        ,"Unable to create user":"ᓴᖅᕿᑦᑎᓂᖅ ᐊᑐᖅᑎᒥᒃ ᐊᔪᖅᑐᖅ"
        ,"Unable to create user: ":"ᓴᖅᕿᑦᑎᓂᖅ ᐊᑐᖅᑎᒥᒃ ᐊᔪᖅᑐᖅ: "
        ,"Unable to delete document {id}":"ᐲᕐᓂᖅ ᑎᑎᖅᖃᖅ ᐊᔪᖅᑐᖅ {id}"
        ,"Unable to delete document. Are you logged in?":"ᐲᕐᓂᖅ ᑎᑎᖅᖃᖅ ᐊᔪᖅᑐᖅ. ᑕᐃᑯᙵᖅᓯᒪᕕᑦ?"
        ,"Unable to delete user document: ":"ᐲᕐᓂᖅ ᐊᑐᖅᑎᒧᑦ ᑎᑎᖅᖃᖅ ᐊᔪᖅᑐᖅ: "
        ,"Unable to display brief description":"ᑕᑯᒃᓴᐅᑎᑦᑎᓂᖅ ᓇᐃᑦᑐᒥᒃ ᐅᖃᐅᓯᖃᖅᑐᒥᒃ ᐊᔪᖅᑐᖅ"
        ,"Unable to display document":"ᑕᑯᒃᓴᐅᑎᑦᑎᓂᖅ ᑎᑎᖅᖃᒥᒃ ᐊᔪᖅᑐᖅ"
        ,"Unable to fetch schema":"ᓂᕈᐊᕐᓗᒍ ᐱᔭᐅᔭᖅᑐᕐᓂᖓ ᐋᖅᕿᒃᓯᒪᔪᖅ"
        ,"Unable to find document search filter":"ᐊᔪᖅᑐᖅ ᓇᓂᓯᓂᖅ ᑎᑎᖅᖃᒥᑦ ᕿᓂᖅᓴᐃᓂᕐᒧᑦ ᓇᓗᓇᐃᒃᑯᑦᑎᖅᓯᒪᔪᑦ"
        ,"Unable to find document transform":"ᐊᔪᖅᑐᖅ ᓇᓂᓯᓂᖅ ᑎᑎᖅᖃᒥᒃ ᐊᓯᐊᙳᖅᓯᔾᔪᑎᒥᒃ"
        ,"Unable to find search filter":"ᐊᔪᖅᑐᖅ ᓇᓂᓯᓂᖅ ᕿᓂᖅᓴᐃᓂᕐᒧᑦ ᓇᓗᓇᐃᒃᑯᑦᑎᖅᓯᒪᔪᑦ"
        ,"Unable to initialize submission database":"ᐊᔪᖅᑐᖅ ᐱᒋᐊᖅᑎᓐᓂᐊᕐᓗᒍ ᑐᓂᓯᓂᖅ ᓈᓴᐅᑎᓂᒃ/ᑎᑎᖅᖃᓂᒃ ᑐᖅᖁᖅᓯᓯᒪᕝᕕᖕᒧᑦ"
        ,"Unable to initiate password recovery. Contact your administrator to resolve this issue.":"ᐊᔪᖅᑐᖅ ᐱᒋᐊᖅᑎᑦᑎᓂᖅ ᑕᐃᑯᙵᕈᖕᓇᐅᑎᒥᒃ ᐅᑎᖅᑎᑦᑎᓂᐊᕐᓗᓂ. ᖃᐅᔨᑎᓪᓗᒍ ᐊᐅᓚᑦᑎᔨᒋᔭᖏᑦ ᐋᖅᕿᖕᓂᐊᕐᓗᒍ ᐱᔾᔪᑕᐅᔪᖅ."
        ,"Unable to load document":"ᐊᔪᖅᑐᖅ ᐊᐅᓪᓚᖅᑎᓐᓂᐊᕐᓗᒍ ᑎᑎᖅᖃᖅ"
        ,"Unable to load import profiles: {err}":"ᐊᔪᖅᑐᖅ ᐊᐅᓪᓚᖅᑎᓐᓂᐊᕐᓗᒍ ᐃᓕᓗᒍ ᐱᔾᔪᑎᖃᖅᑐᓂᒃ: {err}"
        ,"Unable to obtain document {docId}":"ᐊᔪᖅᑐᖅ ᐱᓂᐊᕐᓗᓂ ᑎᑎᖅᖃᒥᒃ {docId}"
        ,"Unable to obtain information about user":"ᐊᔪᖅᑐᖅ ᐱᓂᐊᕐᓗᓂ ᑐᑭᓯᐅᒪᔾᔪᑎᓂᒃ ᐊᑐᖅᑎᐅᑉ ᒥᒃᓵᓄᑦ"
        ,"Unable to obtain list of documents with attachments":"ᐊᔪᖅᑐᖅ ᐱᓂᐊᕐᓗᓂ ᑎᑎᕋᖅᓯᒪᔪᓂᒃ ᑎᑎᖅᖃᓂᒃ ᐃᓚᐅᔪᖃᖅᑐᓂᒃ"
        ,"Unable to obtain list of export scripts":"ᐊᔪᖅᑐᖅ ᐱᓂᐊᕐᓗᓂ ᑎᑎᕋᖅᓯᒪᔪᓂᒃ ᐊᐅᓪᓚᖅᑎᑕᐅᔪᑦ ᑎᑎᕋᖅᓯᒪᔪᓂᒃ"
        ,"Unable to obtain list of import profiles":"ᐊᔪᖅᑐᖅ ᐱᓂᐊᕐᓗᓂ ᑎᑎᕋᖅᓯᒪᔪᓂᒃ ᐃᓕᓗᒍ ᐱᔾᔪᑎᖃᖅᑐᓂᒃ"
        ,"Unable to obtain list of layers":"ᐊᔪᖅᑐᖅ ᐱᓂᐊᕐᓗᓂ ᑎᑎᕋᖅᓯᒪᔪᓂᒃ ᖃᓕᕇᒃᑐᓂᒃ"
        ,"Unable to obtain list of schemas":"ᓂᕈᐊᕐᓗᒍ ᐱᓂᐊᕐᓗᓂ ᑎᑎᕋᖅᓯᒪᔪᑦ ᐋᖅᕿᒃᓯᒪᔪᓂᒃ"
        ,"Unable to obtain list of views":"ᐊᔪᖅᑐᖅ ᐱᓂᐊᕐᓗᓂ ᑎᑎᕋᖅᓯᒪᔪᑦ ᑕᑯᔭᐅᓯᒪᔪᓂᒃ"
        ,"Unable to obtain submission document: {err}":"ᐊᔪᖅᑐᖅ ᐱᓂᐊᕐᓗᓂ ᑐᓂᓯᓗᓂ ᑎᑎᖅᖃᒥᑦ: {err}"
        ,"Unable to obtain user agreement":"ᐊᔪᖅᑐᖅ ᐱᓂᐊᕐᓗᓂ ᐊᑐᖅᑎᒧᑦ ᐊᖏᖃᑎᒌᒍᑎᒥᑦ"
        ,"Unable to parse JSON string: ":"ᐊᔪᖅᑐᖅ ᐅᖃᐅᓯᕆᓂᖅ JSON ᐋᖅᕿᒃᓯᒪᔪᑦ: "
        ,"Unable to parse import data: {err}":"ᐊᔪᖅᑐᖅ  ᐅᖃᐅᓯᕆᓂᖅ ᐃᓕᓗᒍ ᓈᓴᐅᑏᑦ/ᑎᑎᖅᖃᐃᑦ: {err}"
        ,"Unable to parse key: ":"ᐊᔪᖅᑐᖅ ᐅᖃᐅᓯᕆᓂᖅ ᓇᕿᑦᑕᕆᐊᓕᒃ: "
        ,"Unable to preload schemas: {err}":"ᐊᔪᖅᑐᖅ ᐊᐅᓪᓚᖅᑎᑦᑎᕙᒌᕐᓂᖅ ᐋᖅᕿᒃᓯᒪᔪᑦ: {err}"
        ,"Unable to reach database to submit document: {err}":"ᐊᔪᖅᑐᖅ ᑎᑭᐅᑎᓂᖅ ᓈᓴᐅᑎᓄᑦ/ᑎᑎᖅᖃᓄᑦ ᑐᖅᖁᖅᓯᓯᒪᕝᕕᖕᒧᑦ ᑐᓂᓂᐊᕐᓗᒍ ᑎᑎᖅᖃᖅ: {err}"
        ,"Unable to reach server: {err}":"ᐊᔪᖅᑐᖅ ᑎᑭᐅᑎᓂᕐᒧᑦ ᐱᔨᑦᑎᕋᐅᑎᒧᑦ: {err}"
        ,"Unable to recover password":"ᐊᔪᖅᑐᖅ ᐅᑎᖅᑎᑦᑎᓂᖅ ᑕᐃᑯᙵᕈᖕᓇᐅᑎᒥᑦ"
        ,"Unable to recover password: ":"ᐊᔪᖅᑐᖅ ᐅᑎᖅᑎᑦᑎᓂᖅ ᑕᐃᑯᙵᕈᖕᓇᐅᑎᒥᑦ: "
        ,"Unable to register user: ":"ᐊᔪᖅᑐᖅ ᐊᑎᓕᐅᕐᓂᐊᕐᓗᒍ ᐊᑎᖅᑐᐅᔪᖅ: "
        ,"Unable to reload conflicting document":"ᐊᔪᖅᑐᖅ ᐊᐅᓪᓚᖅᑎᒃᑲᓐᓂᕐᓂᐊᕐᓗᒍ ᐃᖢᐃᓗᑕᖅ ᑎᑎᖅᖃᖅ"
        ,"Unable to retrieve document":"ᐊᔪᖅᑐᖅ ᐱᓂᖅ ᑎᑎᖅᖃᒥᒃ"
        ,"Unable to retrieve documents":"ᐊᔪᖅᑐᖅ ᐱᓂᖅ ᑎᑎᖅᖃᓂᒃ"
        ,"Unable to retrieve documents: {err}":"ᐊᔪᖅᑐᖅ ᐱᓂᖅ ᑎᑎᖅᖃᓂᒃ: {err}"
        ,"Unable to retrieve import profiles: {err}":"ᐊᔪᖅᑐᖅ ᐱᓂᖅ ᐃᓕᓗᒍ ᐱᔾᔪᑎᖃᖅᑐᓂᒃ: {err}"
        ,"Unable to retrieve time map resource at {url}":"ᐊᔪᖅᑐᖅ ᐱᓂᖅ ᐱᕕᖃᖅᑐᖅ ᓄᓇᙳᐊᒥᒃ ᐱᕝᕕᐅᔪᖅ ᐅᕙᓂ {url}"
        ,"Unable to save user document: ":"ᐊᔪᖅᑐᖅ ᐊᓯᐊᔨᑦᑕᐃᓕᓂᖅ ᐊᑐᖅᑎᐅᑉ ᑎᑎᖅᖃᐅᑎᖓᓂᑦ: "
        ,"Unable to send e-mail: {err}":"ᐊᔪᖅᑐᖅ ᐊᐅᓪᓚᖅᑎᑦᑎᓂᖅ ᖃᕆᑕᐅᔭᒃᑯᑦ ᑎᑎᖅᖃᑎᒍᑦ: {err}"
        ,"Unable to set password: ":"ᐊᔪᖅᑐᖅ ᐋᖅᕿᒃᓯᓂᕐᒥᒃ ᑕᐃᑯᙵᕈᖕᓇᐅᑎᒥᑦ: "
        ,"Unable to submit document: {err}":"ᐊᔪᖅᑐᖅ ᑐᓂᓯᓂᐊᕐᓗᓂ ᑎᑎᖅᖃᒥᑦ: {err}"
        ,"Unable to update document. Are you logged in?":"ᐊᔪᖅᑐᖅ ᓄᑖᙳᖅᑎᕆᓂᕐᒥᒃ ᑎᑎᖅᖃᒥᒃ. ᑕᐃᑯᙵᖅᓯᒪᕕᑦ?"
        ,"Unable to update submission document: {err}":"ᐊᔪᖅᑐᖅ ᓄᑖᙳᖅᑎᕆᓂᕐᒥᒃ ᑐᓂᔭᐅᔪᖅ ᑎᑎᖅᖃᒥᒃ: {err}"
        ,"Unable to upload file. Cause: {err}":"ᐊᔪᖅᑐᖅ ᐊᐅᓪᓚᖅᑎᑦᑎᓂᖅ ᑎᑎᖅᖃᒥᑦ. ᐱᔾᔪᑕᐅᔪᖅ: {err}"
        ,"Unable to verify password recovery token":"ᐊᔪᖅᑐᖅ ᓇᓗᓇᐃᖅᓯᓂᖅ ᑕᐃᑯᙵᕈᖕᓇᐅᑎᒥᒃ ᐅᑎᖅᑎᑦᑎᓂᕐᒧᑦ ᐊᑐᖅᑕᐅᔪᒥᒃ"
        ,"Unable to verify token":"ᐊᔪᖅᑐᖅ ᓇᓗᓇᐃᖅᑕᐅᓂᖅ ᐊᑐᖅᑕᐅᔪᖅ"
        ,"Uncategorized":"ᐃᓂᓕᐅᖅᑕᐅᓯᒪᙱᑦᑐᖅ"
        ,"Unknown Filter":"ᖃᐅᔨᒪᔭᐅᖏᑦᑐᖅ ᕿᓂᖅᓴᐃᓂᕐᒧᑦ ᓇᓗᓇᐃᒃᑯᑦᑎᖅᓯᒪᔪᑦ"
        ,"Unknown List":"ᖃᐅᔨᒪᔭᐅᖏᑦᑐᖅ ᑎᑎᕋᖅᓯᒪᔪᑦ"
        ,"Unknown Transform":"ᖃᐅᔨᒪᔭᐅᖏᑦᑐᖅ ᐊᓯᐊᙳᕐᓂᖅ"
        ,"Unknown import profile type: {type}":"ᖃᐅᔨᒪᔭᐅᖏᑦᑐᖅ ᐃᓕᓗᒍ ᐱᔾᔪᑎᖃᖅᑐᖅ ᖃᓄᐃᑦᑑᓂᖓ: {type}"
        ,"Unknown schema: {name}":"ᖃᐅᔨᒪᔭᐅᖏᑦᑐᖅ ᓂᕈᐊᕐᓗᒍ ᐋᖅᕿᒃᓯᒪᔪᖅ: {name}"
        ,"Unknown type for help document: {docId}":"ᖃᐅᔨᒪᔭᐅᖏᑦᑐᖅ ᖃᓄᐃᑦᑐᒥᒃ ᐃᑲᔪᖅᑐᖅ ᑎᑎᖅᖃᒧᑦ: {docId}"
        ,"Unsupported Browser":"ᐃᑲᔪᖅᑕᐅᖏᑦᑐᖅ ᖃᕆᑕᐅᔭᒃᑰᕈᑎ"
        ,"Updated document with id: {id}":"ᓄᑖᙳᖅᑎᖅᓯᒪᔪᖅ ᑎᑎᖅᖃᖅ ᓇᓗᓇᐃᖅᓯᔾᔪᑎᖃᖅᖢᓂ: {id}"
        ,"Upgrade Json Application Started":"ᓄᑖᒥᒃ ᐱᓗᓂ Json-ᒧᑦ ᖃᕆᑕᐅᔭᒃᑯᑦ ᐊᑐᖅᑐᒥᒃ ᐱᒋᐊᖅᑐᖅ"
        ,"Upload":"ᑎᑎᖅᑲᒥᒃ ᐃᓕᓯᓗᓂ"
        ,"Upload Media Directory Listing":"ᐊᐅᓪᓚᖅᑎᓪᓗᒍ ᖃᕆᑕᐅᔭᒥᑦ ᐱᔭᐅᔪᖕᓇᖅᑐᑦ ᑎᑎᕋᖅᓯᒪᔪᑦ"
        ,"Upload service can not be reached. Unable to submit a related document.":"ᐊᐅᓪᓚᖅᑎᓪᓗᒍ ᐱᔨᑦᑎᕋᐅᑎ ᑎᑭᐅᑎᔭᐅᓂᖅ ᐊᔪᖅᑐᖅ. ᐊᔪᖅᑐᖅ ᑐᓂᓯᓂᖅ ᐱᔾᔪᑎᖃᖅᑐᒥᒃ ᑎᑎᖅᖃᒥᒃ."
        ,"User":"ᐊᑐᖅᑎ"
        ,"User Agreement":"ᐊᑐᖅᑎᒧᑦ ᐊᖏᖃᑎᒌᒍᑎ"
        ,"User Agreement and Terms of Service":"ᐊᑐᖅᑎᒧᑦ ᐊᖏᖃᑎᒌᒍᑎ ᐊᒻᒪᓗ ᑐᑭᐅᔪᑦ ᐱᔨᑦᑎᕋᐅᑎᒧᑦ"
        ,"User Creation":"ᐊᑐᖅᑎᒥᒃ ᓴᖅᕿᑦᑎᓂᖅ"
        ,"User Questionnaire":"ᐊᑐᖅᑎᒧᑦ ᐊᐱᖅᖁᑏᑦ ᑭᐅᔭᐅᔭᕆᐊᓖᑦ"
        ,"User Registration":"ᐊᑐᖅᑎ ᐊᑎᓕᐅᕐᓗᓂ"
        ,"User agreement has changed. You must accept before you can authenticate.":"ᐊᑐᖅᑎᒧᑦ ᐊᖏᖃᑎᒌᒍᑎ ᐊᓯᐊᙳᖅᑐᖅ. ᓈᒻᒪᒋᔭᕆᐊᖃᖅᑕᐃᑦ ᓇᓗᓇᐃᖅᓯᔾᔪᑎᒋᓂᐊᓵᕐᓗᒍ."
        ,"User created but unable to log in: ":"ᐊᑐᖅᑎᒥᒃ ᓴᖅᕿᑦᑎᔪᖅ ᑭᓯᐊᓂ ᑕᐃᑯᙵᕐᓂᖅ ᐊᔪᖅᑐᖅ: "
        ,"User created successfully.":"ᐊᑐᖅᑎᒥᒃ ᓴᖅᕿᑦᑎᓂᖅ ᓈᒻᒪᒃᑐᖅ."
        ,"User name should have at least 3 characters":"ᐊᑐᖅᑎᐅᑉ ᐊᑎᖓ ᐱᖓᓱᓂᒃ ᑎᑎᖅᖃᖃᕆᐊᖃᖅᑐᖅ ᑐᖔᓂᐅᖏᑦᑐᖅ"
        ,"User refused agreement":"ᐊᑐᖅᑎ ᕿᐱᓗᒃᑕᖓ ᐊᖏᖃᑎᒌᒍᑎ"
        ,"User registration initiated. Check for e-mail to complete user creation":"ᐊᑐᖅᑎᐅᑉ ᐊᑎᓕᐅᕆᓂᖓ ᐱᒋᐊᖅᑎᑕᐅᔪᖅ. ᖃᐅᔨᒋᐊᕐᓗᒍ ᖃᕆᑕᐅᔭᒃᑯᑦ ᑎᑎᖅᖃᐃᑦ ᐱᐊᓂᖕᓂᐊᕐᓗᒍ ᐊᑐᖅᑎᒥᒃ ᓴᖅᕿᑦᑎᓂᖅ"
        ,"Validated E-mail":"ᓇᓗᓇᐃᖅᓯᒪᔪᖅ ᖃᕆᑕᐅᔭᒃᑯᑦ ᑎᑎᖅᖃᒧᑦ ᑐᕌᕈᑎ"
        ,"Verification":"ᓇᓗᓇᐃᖅᓯᓂᖅ"
        ,"Verify":"ᓇᓗᓇᐃᕐᓗᒍ"
        ,"Verify Password":"ᓇᓗᓇᐃᕐᓗᒍ ᑕᐃᑯᙵᕈᖕᓇᐅᑎ"
        ,"Verifying token":"ᓇᓗᓇᐃᖅᓯᔪᖅ ᐃᓕᔭᐅᔪᒥᒃ"
        ,"View":"ᑕᑯᓗᒍ"
        ,"View Media":"ᑕᑯᓗᒍ ᖃᕆᑕᐅᔭᒦᑦᑐᖅ"
        ,"View Original":"ᑕᑯᓗᒍ ᓴᖅᕿᖅᖃᐅᑕᐅᓚᐅᖅᑐᖅ"
        ,"View Submission":"ᑕᑯᓗᒍ ᑐᓂᓯᓂᐊᕐᓗᓂ"
        ,"View Submitted":"ᑕᑯᓗᒍ ᑎᓂᔭᐅᔪᖅ"
        ,"Warning":"ᐅᔾᔨᕆᔭᐅᓕᒃ"
        ,"Warning on Database Submissions":"ᐅᔾᔨᖅᑐᖁᔨᓂᖅ ᓈᓴᐅᑎᓂᒃ/ᑎᑎᖅᖃᓂᒃ ᑐᖅᖁᖅᓯᓯᒪᕝᕕᖕᒧᐊᖅᑎᑕᐅᔪᓄᑦ"
        ,"Welcome":"ᑐᙵᓱᒋᑦ"
        ,"Yes":"ᐄ"
        ,"You are about to delete this document. Do you want to proceed?":"ᐲᕐᓂᐊᖅᑕᐃᑦ ᑎᑎᖅᖃᐅᑎᑦ. ᑲᔪᓯᔪᒪᕕᑦ?"
        ,"You are about to leave this page. Do you wish to continue?":"ᕿᒪᖕᓂᐊᓕᖅᑕᐃᑦ ᒪᒃᐱᖅᑐᒐᖅ. ᑲᔪᓯᔪᒪᕕᑦ?"
        ,"You must agree to the User Agreement before creating a user.":"ᐊᖏᕆᐊᖃᖅᑐᑎᑦ ᐊᑐᖅᑐᐅᔪᒧᑦ ᐊᖏᖃᑎᒌᒍᑎᒥᑦ ᓴᖅᕿᑦᑎᓂᐊᓵᕐᓗᑎᑦ ᐊᑐᖅᑎᒥᑦ."
        ,"You must enter a valid function":"ᐃᓕᓯᔭᕆᐊᖃᖅᑐᑦ ᐊᔪᙱᑦᑐᒥᒃ ᐊᑐᖅᑐᒥᒃ "
        ,"You must first load the database info.":"ᐃᓕᖅᖃᐅᑕᐅᔭᕆᐊᖃᖅᑕᐃᑦ ᓈᓴᐅᑎᓄᑦ/ᑎᑎᖅᖃᓄᑦ ᑐᑭᓯᐅᒪᔾᔪᑎ."
        ,"You must first load the media directory listing.":"ᐃᓕᖅᖃᐅᑕᐅᔭᕆᐊᖃᖅᑕᐃᑦ ᖃᕆᑕᐅᔭᒥᑦ ᐱᔭᐅᔪᖕᓇᖅᑐᑦ ᑎᑎᕋᖅᓯᒪᔪᖅ."
        ,"You must first log in to create a new document.":"ᑕᐃᑯᙵᖅᖃᐅᑕᐅᔭᕆᐊᖃᖅᑐᑎᑦ ᓴᖅᕿᑦᑎᓂᐊᕐᓗᑎᑦ ᓄᑖᒥᒃ ᑎᑎᖅᖃᒥᑦ."
        ,"You must leave the atlas to view this file.":"ᕿᒪᒋᐊᖃᖅᑕᐃᑦ ᓄᓇᙳᐊᖅ ᑕᑯᓂᐊᕐᓗᒍ ᑎᑎᖅᖃᖅ."
        ,"You must provide a display name":"ᑐᓂᓯᔭᕆᐊᖃᖅᑐᑎᑦ ᑕᑯᒃᓴᐅᔪᒧᑦ ᐊᑎᕐᒥᑦ"
        ,"You must provide a message":"ᑐᓂᓯᔭᕆᐊᖃᖅᑐᑎᑦ ᑐᓴᖅᑎᑦᑎᔾᔪᑎᒥᒃ "
        ,"You must provide a password":"ᑐᓂᓯᔭᕆᐊᖃᖅᑐᑎᑦ ᑕᐃᑯᙵᕈᑎᒥᒃ"
        ,"You must provide contact information":"ᑐᓂᓯᔭᕆᐊᖃᖅᑐᑎᑦ ᖃᐅᔨᒋᐊᕐᕕᐅᓂᐊᕐᓗᑎᑦ ᑐᑭᓯᐅᒪᔾᔪᑎᓂᒃ"
        ,"You must provide field: {label}":"ᑐᓂᓯᔭᕆᐊᖃᖅᑐᑎᑦ ᓱᔪᒪᖕᒪᖔᖅᐱᑦ: {label}"
        ,"You must select a file":"ᓂᕈᐊᕆᐊᖃᖅᑐᑎᑦ ᑎᑎᖅᖃᒥᒃ"
        ,"Your browser is not supported by this web site.":"ᑕᐅᑐᒍᑏᑦ ᐃᑲᔪᖅᑕᐅᖏᑦᑐᖅ ᖃᕆᑕᐅᔭᒃᑯᑦ ᑕᑯᒋᐊᖅᑕᕐᕕᖕᒧᑦ."
        ,"Your file was uploaded and will become available when it has been approved.":"ᑎᑎᖅᖃᐃᑦ ᐊᐅᓪᓚᖅᑎᑕᐅᖅᖃᐅᔪᖅ ᐊᒻᒪᓗ ᒪᓂᒪᓕᕐᓂᐊᖅᑐᖅ ᓈᒻᒪᒋᔭᐅᓯᒪᓕᖅᐸᑦ."
        ,"Your message was sent":"ᑎᑎᕋᖅᑕᐃᑦ ᐊᐅᓪᓚᖅᑎᑕᐅᖅᖃᐅᔪᖅ"
        ,"Your password is too short":"ᑕᐃᑯᙵᕈᑏᑦ ᓇᐃᓗᐊᖅᑐᖅ"
        ,"Zoom In":"ᖃᒡᓕᒋᐊᕐᓗᒍ"
        ,"Zoom Out":"ᐅᖓᓯᒃᓯᒋᐊᕐᓗᒍ"
        ,"a Checkbox":"ᓇᓗᓇᐃᖅᓯᔾᔪᑎ ᑭᑉᐹᕆᒃᑐᖅ"
        ,"a Number":"ᓈᓴᐅᑎ"
        ,"a String":"ᐋᖅᕿᒃᓯᒪᔪᑦ"
        ,"an Array":"ᐋᖅᕿᑦᑎᐊᖅᓯᒪᓂᖅ"
        ,"an Object":"ᐱᖁᑎ"
        ,"an image":"ᐊᔾᔨ"
        ,"confirm password":"ᓇᓗᓇᐃᕐᓗᒍ ᑕᐃᑯᙵᕈᖕᓇᐅᑎ"
        ,"creation":"ᓴᖅᕿᑦᑎᓂᖅ"
        ,"csv":"csv"
        ,"deletion":"ᐲᖅᓯᓂᖅ"
        ,"display name":"ᑕᑯᒃᓴᐅᓗᒍ ᐊᑎᖅ"
        ,"e-mail address":"ᖃᕋᓴᐅᔭᒃᑯᑦ ᑎᑎᖅᑲᒃᑯᕕᖓ"
        ,"empty":"ᐃᓗᓕᖃᙱᑦᑐᖅ"
        ,"geojson":"geojson"
        ,"id":"ᓇᓗᓇᐃᖅᓯᔾᔪᑎ"
        ,"is":"ᐅᓇ"
        ,"main site":"ᐃᓂᐅᓗᐊᖅᑐᖅ"
        ,"on":"ᐊᐅᓛᖅᑐᖅ"
        ,"password":"ᑕᐃᑯᙵᕈᖕᓇᕈᑏᑦ:"
        ,"search the atlas":"ᕿᓂᖅᓴᕐᓗᒍ ᓄᓇᙳᐊᖅ"
        ,"top":"ᖄᖓ"
        ,"update":"ᓄᑖᙳᖅᑎᕐᓗᒍ"
        ,"user name":"ᐊᑐᖅᑎᐅᑉ ᐊᑎᖓ"
        ,"{count} document(s)":"{count} ᑎᑎᖅᖃᖅ(ᐃᑦ)"
        ,"{count} document(s) modified.":"{count} ᑎᑎᖅᖃᖅ(ᐃᑦ) ᐋᖅᕿᒋᐊᖅᑕᐅᔪᑦ"
        ,"{docId} deleted":"{docId} ᐲᖅᑕᐅᔪᖅ"
        ,"{docId} transformed and saved":"{docId} ᐊᓯᐊᙳᖅᑕᐅᔪᖅ ᐊᒻᒪᓗ ᐊᓯᐅᔨᑦᑕᐃᓕᔭᐅᑉᓗᓂ"
        ,"{index}/{count}":"{index}/{count}"
        ,"{label} definition ({key}) already exists - not loaded or updated":"{label} ᑐᑭᐅᔪᖅ ({key}) ᐱᑕᖄᓂᒃᑐᖅ - ᐃᓕᙱᑦᑐᖅ ᐅᕝᕙᓘᓐᓃᑦ ᓄᑖᙳᖅᑎᙱᑦᑐᖅ"
    });
    
    if( $ && $.datepicker ) {
        var regional = {
            renderer: $.ui.datepicker.defaultRenderer
            ,monthNames: [
                "ᑕᖀᓇᕐᔪᐊᖅ"
                ,"ᐊᕗᓐᓂᕕᒃ"
                ,"ᓇᑦᑎᐊᑦ"
                ,"ᑎᕆᒡᓗᐃᑦ"
                ,"ᓄᕐᕋᐃᑦ"
                ,"ᒪᓐᓃᑦ"
                ,"ᓴᒡᒐᕈᑦ"
                ,"ᐊᑯᓪᓕᕈᕐᕕᒃ"
                ,"ᐊᒥᕋᐃᔭᕐᕕᒃ"
                ,"ᐅᑭᐅᓖᑦ"
                ,"ᑲᑕᒑᕆᕝᕕᒃ"
                ,"ᐋᒡᔪᓕᕐᕕᒃ"
            ]
            ,monthNamesShort: [
                "ᑕᖀᓇᕐᔪᐊᖅ"
                ,"ᐊᕗᓐᓂᕕᒃ"
                ,"ᓇᑦᑎᐊᑦ"
                ,"ᑎᕆᒡᓗᐃᑦ"
                ,"ᓄᕐᕋᐃᑦ"
                ,"ᒪᓐᓃᑦ"
                ,"ᓴᒡᒐᕈᑦ"
                ,"ᐊᑯᓪᓕᕈᕐᕕᒃ"
                ,"ᐊᒥᕋᐃᔭᕐᕕᒃ"
                ,"ᐅᑭᐅᓖᑦ"
                ,"ᑲᑕᒑᕆᕝᕕᒃ"
                ,"ᐋᒡᔪᓕᕐᕕᒃ"
            ]
            ,dayNames: [
                "ᓴᓇᑦᑕᐃᓕᐅᕌᓂᒃᐸᑦ"
                ,"ᑐᒡᓕᐊ"
                ,"ᐱᖓᔪᐊᑦ"
                ,"ᓯᑕᒻᒥᖅ"
                ,"ᑕᓪᓕᒫᑦ"
                ,"ᓴᓇᑦᑕᐃᓕᐊᕈᓯᖅ"
                ,"ᓴᓇᑦᑕᐃᓕ"
            ]
            ,dayNamesShort: [
                "ᓴᓇᑦᑕᐃᓕᐅᕌᓂᒃᐸᑦ"
                ,"ᑐᒡᓕᐊ"
                ,"ᐱᖓᔪᐊᑦ"
                ,"ᓯᑕᒻᒥᖅ"
                ,"ᑕᓪᓕᒫᑦ"
                ,"ᓴᓇᑦᑕᐃᓕᐊᕈᓯᖅ"
                ,"ᓴᓇᑦᑕᐃᓕ"
            ]
            ,dayNamesMin: [
                "ᓴᓇᑦᑕᐃᓕᐅᕌᓂᒃᐸᑦ"
                ,"ᑐᒡᓕᐊ"
                ,"ᐱᖓᔪᐊᑦ"
                ,"ᓯᑕᒻᒥᖅ"
                ,"ᑕᓪᓕᒫᑦ"
                ,"ᓴᓇᑦᑕᐃᓕᐊᕈᓯᖅ"
                ,"ᓴᓇᑦᑕᐃᓕ"
            ]
            ,dateFormat: 'dd/mm/yyyy'
            ,firstDay: 1
            ,prevText: '&#x3c;ᓯᕗᓂᐊᓃᑦᑐᖅ'
            ,prevStatus: 'ᑕᑯᓗᒍ ᓯᕗᓂᐊᓂᑦ ᑕᖅᕿᐅᓚᐅᖅᑐᖅ'
            ,prevJumpText: '&#x3c;&#x3c;'
            ,prevJumpStatus: 'ᑕᑯᓗᒍ ᓯᕗᓂᐊᓂᑦ ᐅᑭᐅᖑᓚᐅᖅᑐᖅ'
            ,nextText: 'ᑐᒡᓕᐊ&#x3e;'
            ,nextStatus: 'ᑕᑯᓗᒍ ᑕᖅᕿᐅᓂᐊᖅᑐᖅ'
            ,nextJumpText: '&#x3e;&#x3e;'
            ,nextJumpStatus: 'ᑕᑯᓗᒍ ᐅᑭᐅᖑᓂᐊᖅᑐᖅ'
            ,currentText: 'ᒫᓐᓇᐅᔪᖅ'
            ,currentStatus: 'ᑕᑯᓗᒍ ᒫᓐᓇᐅᔪᖅ ᑕᖅᕿᖅ'
            ,todayText: 'ᐅᑉᓗᒥ'
            ,todayStatus: 'ᑕᑯᓗᒍ ᐅᑉᓗᒥᐅᔪᖅ'
            ,clearText: 'ᑕᑯᒃᓴᐅᔪᖅ'
            ,clearStatus: 'ᐲᕐᓗᒍ ᓂᕈᐊᖅᑕᐅᔪᖅ ᐅᑉᓗᖅ'
            ,closeText: 'ᐊᑭᑐᓗᐊᖏᑦᑐᖅ ᒪᓕᖕᓂᕐᒧᑦ'
            ,closeStatus: 'ᐅᒃᑯᐊᕐᓗᒍ ᐋᖅᕿᒃᓱᙱᓪᓗᒍ'
            ,yearStatus: 'ᑕᑯᓗᒍ ᐊᓯᐊ ᐅᑭᐅᖅ'
            ,monthStatus: 'ᑕᑯᓗᒍ ᐊᓯᐊ ᑕᖅᕿᖅ'
            ,weekText: 'ᐱᓇᓱᐊᕈᓯᖅ'
            ,weekStatus: 'ᐱᓇᓱᐊᕈᓯᐅᔪᖅ ᐅᑭᐅᕐᒥᑦ'
            ,dayStatus: 'ᓂᕈᐊᕐᓗᑎᑦ ᐅᑉᓗᕐᒥᑦ ᑕᖅᕿᒥᑦ'
            ,defaultStatus: 'ᓂᕈᐊᕐᓗᑎᑦ ᐅᑉᓗᕐᒥᑦ'
            ,isRTL: false
        };
    
        $.datepicker.setDefaults( regional );
    };
        
    })(jQuery,nunaliit2);
