/*
  Nunaliit2 French Language Pack
*/
;(function($,$n2){

$n2.l10n.addLocalizedStrings('fr',{
	// Language: fr
	" definition (":" définition ("
	," definition (index: ":" définition (indice: "
	," definition null and skipped.":" définition nulle et ignorée"
	," definition: ":" définition"
	,"(by {author})":"(par {author})"
	,"<Unknown error>":"<Erreur inconnue>"
	,"<error>":"<erreur>"
	,"?":"?"
	,"A HTML file must be specified for the customHtml canvas":"Un fichier HTML doit être spécifié pour une toile SVG"
	,"A SVG file must be specified for the customSvg canvas":"Un fichier SVG doit être spécifié pour une toile customSvg"
	,"A database must be provided":"Une base de données doit être spécifiée"
	,"A document identifier must be provided":"Un identificateur de document doit être spécifié"
	,"A file must be selected":"Un fichier doit être sélectionné"
	,"A filter function must be supplied":"Un filtre doit être donné"
	,"A list must be provided for refining":"Durant une spécialisation, une liste doit être donnée"
	,"A list name must be supplied":"Un nom de liste doit être donné"
	//no longer in use: "A list name must be supplied"
	,"A name must be provided when refining a list":"Durant une spécialisation, un nom doit être donné"
	//no longer in use: "A name must be provided when refining a list"
	,"A valid schema must be provided":"Un schème valide doit être donné"
	,"AUTO":"AUTOMATIQUE"
	,"Accept":"Accepter"
	,"Accept User Agreement":"Accepter l'entente de l'utilisateur"
	,"Add":"Ajouter"
	,"Add Comment":"Ajouter un commentaire"
	,"Add File":"Ajouter un fichier"
	,"Add Layer":"Ajouter Couche"
	,"Add Related Item":"Relier"
	,"Add Relation":"Relier"
	,"Add User":"Ajouter un usager"
	,"Add a feature to the map based on a gazetteer service":"Ajouter une géométrie à partir d'un service de nomenclature."
	,"Add a line to the map":"Ajouter une ligne à la carte"
	,"Add a point to the map":"Ajouter un point à la carte"
	,"Add a polygon to the map":"Ajouter un polygone à la carte"
	,"Add or Edit a Map Feature":"Modifier la Carte"
	,"Alert":"Alerte"
	,"All":"Tout"
	,"All Documents":"Tous les documents"
	,"All Geometries":"Toutes les formes géométriques"
	,"All Layers":"Toutes les couches"
	,"All LineString Geometries":"Toutes les géométries de lignes"
	,"All Point Geometries":"Toutes les géométries de points"
	,"All Polygon Geometries":"Toutes les géométries de polygones"
	,"All documents containing {searchTerm}":"Tous les documents contenant {searchTerm}"
	,"All documents filtered by script":"Tous les documents filtré par un programme"
	,"All documents matching regex {regex}":"Tous les documents associés à une expression régulière"
	,"An import profile must be provided":"Un profil d'importation doit être spécifié"
	,"Approve":"Approuver"
	,"Attach":"Joindre"
	,"Attachment":"Pièce jointe"
	,"Attachment Name":"Nom de la pièce jointe"
	,"Attachment has been denied":"La pièce jointe fut rejetée"
	,"Attachment is being processed":"Travail en cours sur la pièce jointe"
	,"Attachment is waiting for approval":"Pièce jointe en attente de l'approbation"
	,"Attachment: ":"Pièce jointe: "
	//no longer in use: "Attachment: "
	,"Authentication service must be configured":"Le service d'identité doit être configuré"
	,"Author":"Auteur"
	,"Available Layers":"Couches disponibles"
	,"Back":"Retour"
	,"Bad Proxy Circumvention":"Contournement des serveurs proxy"
	,"Base Layer":"Couche de Fond"
	,"Body":"Corps"
	,"Brief":"Brève Affichage"
	,"By":"Par"
	,"COLLISION":"COLLISION"
	,"CSS":"CSS"
	,"CSV":"CSV"
	,"Can not find import profile with id: {id}":"Impossible de trouver le profil d'importation: {id}"
	,"Can not parse date":"Impossible d'interpréter la date"
	,"Can not perform file uploads unless jquery.form.js is included":"jquery.form.js est nécessaire pour le téléchargement de fichier"
	,"Cancel":"Annuler"
	,"Cancel Feature Editing":"Annuler les modifications"
	,"Cancelling Operation...":"Annuler l'opération..."
	,"Capture Photo":"Prendre photo"
	,"Capture Video":"Prendre video"
	,"Capture Audio":"Prendre audio"
	,"Change Password":"Changer Mot de Passe"
	,"Choose File":"Choisir fichier"
	,"Clear":"Vider"
	,"Click here to return to main site: ":"Retourner à la page principale: "
	,"Close":"Fermer"
	,"Collision on Geometry":"Collision contre la géométrie"
	,"Collision on property {property}":"Collision contre l'attribut {property}"
	,"Commands for removal":"Instructions de suppression"
	,"Comment":"Commentaire"
	,"Compiling records":"Compilation des annales"
	,"Configuration":"Configuration"
	,"Confirm":"Confirmer"
	,"Confirm password:":"Vérifier mot de passe"
	,"Contact Information":"Coordonnées"
	,"Content":"Contenue"
	,"Contribution":"Contribution"
	//no longer in use: "Contribution"
	,"Converted":"Converti"
	,"Create Document":"Nouveau Document"
	,"Create User":"Création d'usager"
	,"Create a new user":"Créer un nouvel usager"
	,"Create feature from name":"Créer une géométrie à partir d'un nom"
	,"Create new document":"Créer un nouveau document"
	,"Create {label}":"Créer {label}"
	,"Created by":"Créer par"
	,"Created document with id: {id}":"Nouveau document créé: {id}"
	,"Creating a user associated with the e-mail address: {address}":"Creation d'un usager associé avec l'adresse courriel: {address}"
	,"Current Location":"Position actuelle"
	,"Custom Script":"Scripte sur mesure"
	,"Data Modification Application":"Application de modification des données"
	,"Date":"Date"
	,"Debug Application":"Application de débogage"
	,"Debug Configuration":"Configuration de débogage"
	,"Default":"Défaut"
	,"Delete":"Supprimer"
	,"Delete Database Document":"Supprimer document de la base de données"
	,"Delete document":"Supprimer le document"
	,"Delete existing document":"Supprimer le document existant"
	,"Deleted document with id: {id}":"Document supprimé: {id}"
	,"Deletion Progress":"Progrès de suppression"
	,"Demo Document":"Document de Démonstration"
	,"Demo Media":"Média de Démonstration"
	,"Deny":"Rejetter"
	//no longer in use: "Deny"
	,"Description":"Description"
	,"Disable":"Désactiver"
	,"Discard":"Jeter"
	,"Dispatcher Event Logging":"Enregistrement des évènement du répartiteur"
	,"Display":"Affichage"
	,"Display Name":"Nom d'affichage"
	,"Do not show again":"Supprimer la prochaine fois"
	,"Do not show this warning again":"Supprimer cet avertissement"
	,"Do you really want to delete this feature?":"Voulez-vous vraiment supprimer cette géométrie?"
	,"Do you really wish to delete the {count} document(s) referenced by this list?":"Désirez-vous supprimer les {count} document(s) contenu dans cette liste?"
	,"Do you wish to delete this element?":"Désirez-vous supprimer cet élément?"
	,"Do you wish to leave document editor?":"Désirez-vous quitter l'éditeur de document?"
	,"Doc ids must be supplied when creating a list from document ids":"Les identificateurs de documents doit être donnés durant la création de cette liste"
	,"Document Id":"Identificateur de document"
	,"Document Identifiers":"Identificateurs de documents"
	,"Document was modified and changes will be lost. Do you wish to continue?":"Le document est modifié et les changements seront perdus. Voulez-vous continuer?"
	,"Document: {id}":"Document: {id}"
	,"Documents from import profile: {profileId}":"Documents associés avec le profil d'importation: {profileId}"
	,"Documents from layer {layerName}":"Documents de la couche {layerName}"
	,"Documents from schema type {schemaName}":"Documents de type de schème {schemaName}"
	,"Documents from view {label}":"Documents du point de vue {label}"
	,"Documents not reachable by reference":"Documents non-accessible par liens"
	,"Documents referencing {docId}":"Les documents en référence de {docId}"
	,"Documents that are invalid":"Documents invalides"
	,"Documents that have an invalid source":"Documents avec une source invalide"
	,"Documents with dangling references":"Documents avec des liens invalides"
	,"Documents with media files in analyzed state":"Documents avec des médias numériques en phase analysée"
	,"Documents with media files in approved state":"Documents avec des médias numériques en phase approuvée"
	,"Documents with media files in attached state":"Documents avec des médias numériques en phase jointe"
	,"Documents with media files in submitted state":"Documents avec des médias numériques en phase soumise"
	,"Documents with media files in waiting state":"Documents avec des médias numériques en phase d'attente"
	,"Done":"Complété"
	,"Done.":"Complété."
	,"Download":"Télécharger"
	,"E-Mail address must be specified":"Adresse courriel doit être spécifié"
	,"E-mail":"Courriel"
	,"E-mail Form":"Formulaire Courriel"
	,"E-mail Template":"Gabarit de message courriel"
	,"E-mail addresses":"Adresses courriel"
	,"E-mail me my password":"Envoyez-moi un courriel avec mon mot de passe"
	,"E-mails":"Courriels"
	,"Edit":"Modifier"
	,"Edit Proposed Document":"Modifier le document proposé"
	,"Edit User":"Modifier l'usager"
	,"Editor View":"Perspective d'Éditeur"
	,"Empty search results":"Résultats de recherche vide"
	,"Enable":"Activer"
	,"Enabled":"Activé"
	,"Enter Report Script":"Entrez le scripte de rapport"
	,"Enter password:":"Entrez mot de passe"
	,"Enter reason for rejecting submission":"Donnez la raison pour la réjection"
	,"Error":"Erreur"
	,"Error attempting to accept user agreement":"Erreur durand le processus d'accepter l'entente de l'utilisateur"
	,"Error creating ":"Erreur de création"
	,"Error creating document":"Erreur durant la création du document"
	,"Error creating import profile. Unknown operation string: {string}":"Erreur durant création de profil d'importation. Opération inconnue: {string}"
	,"Error creating import profile: {err}":"Erreur durant création de profil d'importation: {err}"
	,"Error deleting document":"Erreur durant la suppression du document"
	,"Error during export":"Erreur pendant l'exportation"
	,"Error fetching attachment from help document":"Erreur durand l'obtention du document d'aide"
	,"Error loading CSS from location: {url}":"Erreur durand l'obtention du fichier CSS: {url}"
	,"Error loading HTML from location: {url}":"Erreur durand l'obtention du fichier HTML: {url}"
	,"Error loading SVG from location: {url}":"Erreur durand l'obtention du fichier SVG: {url}"
	,"Error loading documents from database: {err}":"Erreur durand l'obtention d'un document de la base de données: {err}"
	,"Error obtaining user document for {id}: {err}":"Erreur durand l'obtention du document {id}: {err}"
	,"Error occurred after document was saved. Error: {err}":"Erreur détectée après que le document fut sauvegardé: {err}"
	//no longer in use: "Error occurred after document was saved. Error: {err}"
	,"Error occurred after related document was created. Error: {err}":"Erreur détectée après que le document fut créé: {err}"
	,"Error occurred with progress service":"Erreur avec service de progrès"
	,"Error reloading conflicting document during deletion":"Erreur durant la suppression du document (conflit)"
	,"Error updating document":"Erreur durant la mise à jour du document"
	,"Error while analyzing import: {err}":"Erreur durand l'analyze de l'importation: {err}"
	,"Error while updating document {id}":"Erreur durant la mise à jour du document {id}"
	,"Error while uploading: ":"Erreur de téléchargement"
	,"Error: query error while verifying {label} definition ({key})":"Erreur: interrogation échouée lors de la vérification de la définition {label} ({key})"
	,"Errors in process: {count}.":"Nombre d'erreurs: {count}"
	//no longer in use: "Errors in process: {count}."
	,"Export":"Exporter"
	,"Export Error":"Erreur durant l'opération d'exportation"
	,"Export Geometries":"Exportation des géométries"
	//no longer in use: "Export Geometries"
	,"Export by Script":"Exporter à l'aide d'un scripte"
	,"Export service is not available":"Le service d'exportation n'est pas en ligne"
	,"Export service is not configured":"Le service d'exportation n'est pas configuré"
	,"Exporting":"Exportation en marche"
	,"Extent (Max X)":"Étendue (max x)"
	,"Extent (Max Y)":"Étendue (max y)"
	,"Extent (Min X)":"Étendue (min x)"
	,"Extent (Min Y)":"Étendue (min y)"
	,"Failure to delete {docId}":"Impossible de supprimer {docId}"
	,"Failure to fetch {docId}":"Impossible d'obtenir {docId}"
	,"Failure to save {docId}":"Impossible de sauvegarder {docId}"
	,"Fetching All Document Ids":"Obtention de tous les identificateurs de document"
	,"File":"Fichier"
	,"File Name":"Nom du fichier"
	//no longer in use: "File Name"
	,"File Name:":"Nom du fichier:"
	,"File Uploaded":"Fichier téléchargé"
	,"File is not currently available":"Le ficher n'est pas disponible"
	,"Fill Out Related Document":"Composer un document joint"
	,"Fill Out Reply":"Composer une réponse"
	,"Fill out content of new document":"Composer un nouveau document"
	,"Filter:":"Filtre"
	,"Find on Map":"Trouver sur la Carte"
	,"First Name":"Prénom"
	,"Form":"Formulaire"
	,"Form View":"Perspective Formulaire"
	,"Format:":"Format"
	,"From":"De"
	,"Function Transformation":"Fonction de Transformation"
	,"Function is required on transformation":"Une fonction est nécessaire durant les transformations"
	,"GeoJSON definition must include an array named \"features\"":"Une définition GeoJSON doit contenir une liste \"features\""
	,"GeoJSON import is supported only for type \"FeatureCollection\"":"L'importation d'une structure GeoJSON est possible seulment pour le type \"FeatureCollection\""
	,"Geometries":"Géométries"
	,"Geometries from layer {layerName}":"Les géométries de la couche {layerName}"
	,"Geometry":"Géometrie"
	,"Get a different password":"Obtenir un mot de passe différent"
	,"Graph application started":"Application graphique a démarré"
	,"Guest Login":"Session pour visiteur"
	,"Help":"Aide"
	,"Hover Sound":"Son descriptif"
	,"Hover Sound?":"Son descriptif?"
	,"I have forgotten my password":"J'ai oublié mon mot de passe"
	,"I want to choose my own password":"Je veux choisir mon propre mot de passe"
	,"ID":"ID"
	,"Identifier":"Identificateur"
	,"Import Profile":"Profil d'importation"
	,"Import data must be provided":"Données d'importation sont nécessaires"
	,"Imported entry does not contains an id attribute":"Entrée d'importation doit contenir un attribut d'identification"
	,"In reply to":"En réplique à"
	//no longer in use: "In reply to"
	,"Information to contact you":"Information pour vous rejoindre"
	,"Inline":"En ligne"
	,"Input":"Entrer"
	,"Interval":"Intervalle"
	,"Interval max must be a number":"Le maximum d'un intervalle doit être un chiffre"
	,"Interval min can not be greater than max":"Le minimum d'un intervalle ne peut pas être plus grand que le maximum"
	,"Interval min must be a number":"Le minimum d'un intervalle doit être un chiffre"
	,"Introduction":"Introduction"
	,"Invalid attachment in help document":"Problème avec le document d'aide"
	,"Invalid content in help document":"Problème avec le contenu du document d'aide"
	//no longer in use: "Invalid content in help document"
	,"Invalid date structure":"Structure de date invalide"
	,"Invalid date: {err}":"Date invalide: {err}"
	,"Invalid document":"Document invalide"
	,"Invalid e-mail and/or password":"Problème avec votre nom d'usager ou votre mot de passe"
	,"Invalid help document content":"Problème avec le contenu du document d'aide"
	//no longer in use: "Invalid help document content"
	,"Invalid help document: {docId}":"Problème avec le document d'aide: {docId}"
	,"Invalid result returned by GeoNames":"Problèmes avec les résultats obtenus de GeoNames"
	,"Invalid search results returned":"Problèmes avec les résultats de recherche"
	,"Invalid server response":"Problèmes avec la réponse du serveur"
	,"Invalid submission document":"Soumission invalide"
	,"It appears that {count} changes can be completed automatically. Accept automatic changes?":"Il y a {count} changements automatiques. Voulez-vous procéder?"
	,"JSON definition must be an array":"Définition JSON doit être une liste"
	,"JSON definition must be provided":"Définition JSON est nécessaire"
	,"JSON library not available":"Support JSON n'est pas disponible"
	,"JSON.parse() is not available":"JSON.parse() n'est pas disponible"
	,"Javascript":"Javascript"
	,"Javascript Replace":"Remplacer par Javascript"
	,"Key already in use: ":"Clé déjà utilisée: "
	,"Label":"Intitulé"
	,"Language":"Langue"
	,"Last Name":"Dernier Nom"
	,"Last updated by":"Mis-à jour par"
	,"Layer":"Couche"
	,"Layer Definition":"Définition de Couche"
	,"Layer Selector":"Sélecteur de couches"
	,"Layer Selector Initially Opened":"Sélecteur de couches initialement ouvert"
	,"Layer Selector Suppressed":"Sélecteur de couches supprimé"
	,"Layer name":"Nom de couche"
	,"Layers":"Couches"
	,"Less":"Moins"
	,"List Creation Progress":"Progrès de la création de liste"
	,"List Refinement Progress":"Progrès du refinement de liste"
	,"List is required on transformation":"Une liste est nécessaire durant les transformations"
	,"Load Info From Database":"Charger l'information de la base de données"
	,"Load Listing of Media Directory":"Charger la liste des fichiers médiatiques"
	,"Loading document: ":"Chargement de document"
	,"Loading import profiles":"Chargement des profils d'importation"
	,"Loading...":"Chargement en cours..."
	,"Location of CSS is undefined for customHtml canvas":"Une toile customHtml doit spécifier un fichier CSS"
	,"Location of CSS is undefined for customSvg canvas":"Une toile customSvg doit spécifier un fichier CSS"
	,"Location of HTML is undefined for customHtml canvas":"Une toile customHtml doit spécifier un fichier HTML"
	,"Location of SVG is undefined for customSvg canvas":"Une toile customSvg doit spécifier un fichier SVG"
	,"Login":"Ouvrir session"
	,"Logout":"Fermer session"
	,"Logs":"Journal"
	,"Made with Nunaliit":"Construit avec Nunaliit"
	,"Media":"Média"
	//no longer in use: "Media"
	,"Media Application":"Application médiatique"
	,"Media application started":"Application médiatique a débuté"
	,"Media({docId},{attName})":"Média({docId},{attName})"
	,"Message":"Message"
	,"Metadata":"Metadata"
	,"Metadata Editor":"Metadata Editor"
	,"Missing input. Can not proceed.":"Données manquantes. Impossible de continuer"
	,"Model Browser":"Navigateur à modèles"
	,"Models":"Modèles"
	,"Modify Document":"Modifier le document"
	,"Modify existing document":"Modifier le document existant"
	,"Module":"Module"
	,"More":"Plus"
	,"More Details":"Plus de détails"
	,"More Info":"Détails"
	,"More lines... ({num})":"Plus de lignes... ({num})"
	,"More than one import entries report identifier: {id}":"Plusieurs entrées d'importation avec l'identificateur: {id}"
	,"Must enter a document identifier":"Vous devez préciser un identificateur de document"
	,"Must enter a layer name":"Nom de couche manquant"
	,"Must enter a schema name":"Nom de schème manquant"
	,"Must select a view":"Point de vue manquant"
	,"Must select an import profile":"Vous devez préciser un profil d'importation"
	,"My User":"Mon utilisateur"
	,"Name":"Nom"
	,"Name of new list":"Nom de la nouvelle liste"
	//no longer in use: "Name of new list"
	,"Navigation":"Navigation"
	,"New File":"Nouveau Fichier"
	,"Next":"Prochain"
	,"No":"Non"
	//no longer in use: "No"
	,"No Document":"Aucun document"
	,"No changes detected in the import data":"Aucun changement dans les données importées"
	,"No document found":"Aucun document trouvé"
	,"No document modified.":"Aucun document modifié."
	//no longer in use: "No document modified."
	,"No list Selected":"Aucune liste sélectionée"
	,"No media found on {docId}":"Aucun média trouvé avec {docId}"
	//no longer in use: "No media found on {docId}"
	,"No results returned by search":"Aucun résultat de recherche"
	,"No submission available":"Aucune soumission disponible"
	,"Number of documents: {count}":"Nombre de documents: {count}"
	,"Nunaliit Atlas":"Atlas Nunaliit"
	,"Nunaliit Graph":"Graphe Nunaliit"
	,"OK":"Accepter"
	,"Ongoing time interval must begin before now":"Intervalle en cours doit débuter dans le passé"
	,"Only LineString Geometries":"Seulement les géometries de lignes"
	,"Only Point Geometries":"Seulement les géometries de points"
	,"Only Polygon Geometries":"Seulement les géometries de polygones"
	,"Operation cancelled by user":"Opération annulée par l'usager"
	,"Operation not recognized":"Opération inconnue"
	,"Operation {index} of {count}":"Opération {index} de {count}"
	,"Order":"Ordre"
	,"Original":"Original"
	,"Original Id":"Identificateur original"
	,"Original String":"Chaîne de caractères originale"
	,"Overlays":"Calques"
	,"Password":"Mot de Passe"
	,"Password Recovery":"Récupération de mot de passe"
	,"Password Recovery Failure":"Erreur durant la récupération du mot de passe"
	,"Password Recovery Initiated":"Une récupération de mot de passe a débuté"
	,"Password is too short":"Mot de passe est trop court"
	,"Password recovery initiated. Check for an e-mail to complete password recovery":"Une récupération de mot de passe a débuté. Vérifiez vos courriels pour continuer le processus."
	,"Password should have at least 6 characters":"Le mot de passe devrait contenir au moins 6 caractères"
	,"Password was recovered successfully.":"Le mot de passe est récupéré"
	,"Passwords do not match":"Mots de passe sont différents"
	,"Perform Analysis":"Débuter l'analyze"
	,"Please login":"Ouverture de session"
	,"Please, wait until download starts. It might take a while.":"SVP, attendre que le téléchargement commence."
	,"Preparing Report":"Préparation du rapport"
	,"Previous":"Précédent"
	,"Preview":"Apperçu"
	,"Problem obtaining documents from import profile":"Problème détecté pendant l'obtention des documents à partir d'un profil d'importation"
	,"Problem obtaining documents from layer":"Problème détecté pendant l'obtention des documents d'une couche"
	,"Problem obtaining documents from schema":"Problème détecté pendant l'obtention des documents d'un type de schème"
	,"Problem obtaining documents from view":"Problème détecté pendant l'obtention des documents d'un point de vue"
	,"Problem obtaining documents with media files in analyzed state":"Problème détecté pendant l'obtention de fichiers médiatiques dans la phase analyzée"
	,"Problem obtaining documents with media files in approved state":"Problème détecté pendant l'obtention de fichiers médiatiques dans la phase approuvée"
	,"Problem obtaining documents with media files in attached state":"Problème détecté pendant l'obtention de fichiers médiatiques dans la phase jointe"
	,"Problem obtaining documents with media files in submitted state":"Problème détecté pendant l'obtention de fichiers médiatiques dans la phase soumise"
	,"Problem obtaining documents with media files in waiting state":"Problème détecté pendant l'obtention de fichiers médiatiques dans la phase d'attente"
	,"Problem obtaining skeleton documents":"Problème détecté pendant l'obtention des documents squelettes"
	,"Proceed":"Procéder"
	,"Proceed with Import Operations":"Continuer avec l'importation"
	,"Process completed.":"Processus complété."
	//no longer in use: "Process completed."
	,"Progress":"Progrès"
	,"Queries":"Interrogations"
	,"Query Users":"Interrogation des usagers"
	,"Range":"Portée"
	,"Re-Submit Geometries":"Resoumettre les géométries"
	,"Re-Submit Media":"Resoumettre les média"
	,"Record":"Enregistrer"
	//no longer in use: "Re-Submit Media"
	,"Recover Password":"Récupérer un mot de passe"
	,"Recovering password for a user associated with the e-mail address: {address}":"Récupération du mot de passe de l'utilisateur associé avec l'adresse courriel: {address}"
	,"Reference":"Référence"
	,"Reference:":"Référence:"
	,"References":"Références"
	,"Refine List":"Spécialiser la liste"
	,"Refresh":"Rafraîchir"
	,"Regex Expression":"Expression régulière"
	,"Regex Search":"Recherche par expression régulière"
	,"Registration Initiated":"L'enregistrement a débuté"
	,"Reject":"Refuser"
	,"Relation: ":"Relation"
	,"Remind me later":"Rappelez-moi plus tard"
	,"Remove":"Supprimer"
	,"Replace Text":"Texte de remplacement"
	,"Reply":"Répondre"
	,"Report":"Rapport"
	,"Required fields missing for ":"Champs nécessaires manquants pour "
	,"Reset":"Redémarrer"
	,"Reset Password":"Remise à zéro du mot de passe"
	,"Reset password?":"Remise à zéro du mot de passe?"
	,"Resolution":"Résolution"
	,"Revision":"Version"
	,"Roles":"Roles"
	,"Root Schema":"Schème de Base"
	,"STOPPING: Failed verifying view ":"ARRET. Impossible de vérifier la perspective. "
	,"Save":"Sauvegarder"
	,"Schema":"Schème"
	,"Schema Display":"Affichage de schème"
	,"Schemas":"Schèmes"
	,"Script":"Scripte"
	,"Script(":"Scripte("
	,"Script:":"Scripte:"
	,"Scroll Map":"Faire défiler la carte"
	,"Search":"Rechercher"
	,"Search Terms":"Texte de recherche"
	,"Search result is empty":"Recherche sans résultats"
	,"Search results empty":"Recherche sans résultats"
	,"Search term":"Terme recherché"
	//no longer in use: "Search term"
	,"Search terms":"Texte de recherche"
	,"Search:":"Rechercher:"
	,"Select":"Choisir"
	,"Select Document":"Choisir Document"
	,"Select Document Schema":"Choisir un schème de document"
	,"Select Document Transform":"Choisir une transformation de document"
	,"Select Language":"Choisir une Langue"
	,"Select Layers":"Choisir couches"
	,"Select Roles":"Choisir les Roles"
	,"Select Search Filter":"Choisir un filtre de recherche"
	,"Select a media":"Choisir un média"
	,"Select a schema":"Choisir un schème"
	,"Select a schema:":"Choisir un schème:"
	,"Select application started":"L'application de sélection a débuté"
	,"Select documents from a layer":"Choisir les documents d'une couche"
	,"Select documents from a schema type":"Choisir les documents d'un type de schème"
	,"Select documents from an import profile":"Choisir les documents à partir d'un profil d'importation"
	,"Select documents reported in a view":"Choisir les documents à partir d'un point de vue"
	,"Select documents that are not reachable by reference":"Choisir les documents qui ne sont pas disponibles au travers des liens"
	,"Select documents that have an invalid source":"Choisir les documents avec une source invalide"
	,"Select documents that have broken references":"Choisir les documents avec liens invalides"
	,"Select documents that reference another one":"Choisir les documents qui référencent un autre"
	,"Select documents with analyzed media files":"Choisir les documents contenant des fichiers médiatiques en phase d'analyze"
	,"Select documents with approved media files":"Choisir les documents contenant des fichiers médiatiques en phase approuvée"
	,"Select documents with attached media files":"Choisir les documents contenant des fichiers médiatiques en phase jointe"
	,"Select documents with submitted media files":"Choisir les documents contenant des fichiers médiatiques en phase soumise"
	,"Select documents with waiting media files":"Choisir les documents contenant des fichiers médiatiques en phase d'attente"
	,"Select from Javascript":"Choisir à partir de Javascript"
	,"Select geometries from a layer":"Choisir les géométries d'une couche"
	,"Select invalid documents":"Choisir documents invalides"
	,"Select schema":"Choisir un schème"
	,"Select skeleton documents":"Choisir documents squelettes"
	,"Send":"Envoyer"
	,"Send e-mail to submitter with reason for rejection":"Envoyer la raison de réjection par courriel"
	,"Send mail to {name}":"Envoyer un courriel à {name}"
	,"Send us information":"Écrivez-nous"
	,"Server must be specified for CouchDb AuthService":"Le service d'autentification a besoin d'un serveur"
	,"Set Password":"Changer Mot de Passe"
	,"Show":"Montrer"
	,"Show my password":"Montrer mon mot de passe"
	,"Skeleton documents":"Documents squelettes"
	,"Sticky Nodes":"Points Immobiles"
	,"Stop":"Arrêter"
	,"Subject":"Sujet"
	,"Submission Id":"Identificateur de soumission"
	,"Submission State":"État de la soumission"
	,"Submission Type":"Type de soumission"
	,"Submission approved":"Soumission approuvée"
	,"Submission denied":"Soumission rejetée"
	,"Submissions to the database will not appear until they are approved":"Les soumissions à la base de données ne seront pas visibles avant l'approbation"
	,"Submitter":"Usage qui a suggéré la soumission"
	,"Tangibles Application":"Application tangible"
	,"Tangibles application started":"Application tangible a démarré"
	,"Temporary View":"Perspective temporaire"
	,"Test Temporary View":"Tester une perspective temporaire"
	,"Text":"Texte"
	,"Text Replace":"Remplacer le texte"
	,"Text Search":"Rechercher un texte"
	//no longer in use: "Text Search"
	,"The information is expired.":"L'information est périmée"
	,"The mail subject, if specified, must be a string":"Le sujet du courriel, si précisé, doit être une chaîne de caractères"
	,"The projection {srsName} is not supported. Atlas may no function properly.":"La projection {srsName} n'est pas disponible, L'atlas pourrait tomber en panne."
	,"The provided passwords must match":"Les mots de passe doivent être identiques"
	,"The two passwords should match":"Les deux mots de passe devrait être pareils"
	,"There was a problem saving your answers. You will be prompted again next time you log in.":"Problèmes détectés pendant la sauvegarde de vos réponses. Vous serez questionnés à nouveau lors de la prochaine connexion."
	,"This appears to be the first time that you are importing this profile. Accept all?":"Première opportunité d'importer ce profil. Voulez-vous automatiquement accepter toutes les données?"
	,"This cluster contains {count} features":"Ce groupe contient {count} géométries"
	,"This feature is a cluster and can not be edited directly. Please, zoom in to see features within cluster.":"Vous essayez d'éditer un groupe. SVP, rapprocher la carte pour voir les géométries individuelles."
	,"This object is being modified. Do you wish to continue and revert current changes?":"L'objet en cours d'être modifié. Désirez-vous continuer?"
	,"This page must be called from a link received in an e-mail":"Cette page doit être ouverte à partir d'un lien reçu dans un courriel"
	,"Title":"Titre"
	,"To":"À"
	,"Transform":"Transformer"
	,"Transform Progress":"Progrès de la transformation"
	,"Transformations completed with some failures":"Transformations complétées. Erreurs détectées."
	,"Transformations completed. Successful: {ok} Failures: {fail} Skipped: {skipped}":"Transformations complétées. Accomplies: {ok} Erreurs: {fail} Ignorées: {skipped}"
	,"Translation":"Traduction"
	,"Tree Display":"Affichage en Arbre"
	,"Tree View":"Perspective en Arbre"
	,"Type":"Type"
	,"Type of refinement":"Type de spécialisation"
	,"Unable to access help document: {docId}":"Impossible d'accéder le document d'aide: {docId}"
	,"Unable to complete operation : {err}":"Impossible de compléter l'opération: {err}"
	,"Unable to complete operation because the user information has been updated.":"Impossible de compléter l'opération parce que l'information associé avec l'utilisateur fut modifiée."
	,"Unable to create a new list":"Impossible de créer une nouvelle liste"
	,"Unable to create document. Are you logged in?":"Impossible de créer un document. Besoin d'ouvrir une session?"
	,"Unable to create user":"Impossible de créer un nouvel utilisateur"
	,"Unable to create user: ":"La création d'usager a échoué"
	,"Unable to delete document {id}":"Impossible de supprimer le document {id}"
	,"Unable to delete document. Are you logged in?":"Impossible de supprimer le document. Besoin d'ouvrir une session?"
	,"Unable to delete user document: ":"Incapable de supprimer le document d'usager"
	,"Unable to display brief description":"Impossible d'afficher la brève description"
	,"Unable to display document":"Impossible d'afficher le document"
	,"Unable to fetch schema":"Impossible d'obtenir le schème"
	,"Unable to find document search filter":"Impossible de trouver le filtre de recherche"
	,"Unable to find document transform":"Impossible de trouver la transformation"
	,"Unable to find search filter":"Impossible de trouver le filtre de recherche"
	,"Unable to initialize submission database":"Impossible d'initialiser la base de données pour soumissions"
	,"Unable to initiate password recovery. Contact your administrator to resolve this issue.":"Impossible de récupérer le mot de passe. Contactez votre administrateur."
	,"Unable to load document":"Impossible de charger le document"
	,"Unable to load import profiles: {err}":"Impossible de charger les profils d'importation: {err}"
	,"Unable to obtain document {docId}":"Impossible d'obtenir le document {docId}"
	//no longer in use: "Unable to obtain document {docId}"
	,"Unable to obtain information about user":"Impossible d'obtenir l'information associé avec l'utilisateur"
	,"Unable to obtain list of documents with attachments":"Impossible d'obtenir la liste des documents avec pièces jointes"
	,"Unable to obtain list of export scripts":"Impossible d'obtenir la liste des scriptes d'exportation"
	,"Unable to obtain list of import profiles":"Impossible d'obtenir la liste des profils d'importation"
	,"Unable to obtain list of layers":"Impossible d'obtenir la liste des couches"
	,"Unable to obtain list of schemas":"Impossible d'obtenir la liste des schèmes"
	,"Unable to obtain list of views":"Impossible d'obtenir la liste des points de vue"
	,"Unable to obtain submission document: {err}":"Impossible d'obtenir la soumission: {err}"
	,"Unable to obtain user agreement":"Impossible d'obtenir l'entente de l'utilisateur"
	,"Unable to parse JSON string: ":"Incapable de lire l'expression JSON: "
	,"Unable to parse import data: {err}":"Incapable de lire les données importées: {err}"
	,"Unable to parse key: ":"Incapable de comprendre la clé: "
	,"Unable to preload schemas: {err}":"Incapable de pré-charger les schèmes: {err}"
	,"Unable to reach database to submit document: {err}":"Incapable de contacter la base de données pour soumissions"
	,"Unable to reach server: {err}":"Incapable de contacter le serveur: {err}"
	,"Unable to recover password":"Incapable de récupérer le mot de passe"
	,"Unable to recover password: ":"Incapable de récupérer le mot de passe: "
	//no longer in use: "Unable to recover password: "
	,"Unable to register user: ":"Incapable d'enregistrer l'utilisateur"
	,"Unable to reload conflicting document":"Impossible de télécharger le document en conflit"
	,"Unable to retrieve document":"Impossible de trouver le document"
	,"Unable to retrieve documents":"Impossible de trouver les documents"
	,"Unable to retrieve documents: {err}":"Impossible de trouver les documents: {err}"
	,"Unable to retrieve import profiles: {err}":"Incapable de charger les profils d'importation: {err}"
	,"Unable to retrieve time map resource at {url}":"Incapable de charger la carte de temps: {url}"
	,"Unable to save user document: ":"Incapable de sauvegarder le document d'usager"
	,"Unable to send e-mail: {err}":"Incapable d'envoyer votre courriel: {err}"
	,"Unable to set password: ":"Impossible de changer le mot de passe"
	,"Unable to submit document: {err}":"Impossible de sauvegarder le document: {err}"
	,"Unable to update document. Are you logged in?":"Impossible de modifier un document. Besoin d'ouvrir une session?"
	,"Unable to update submission document: {err}":"Incapable de mettre à jour le document de soumission"
	,"Unable to upload file. Cause: {err}":"Incapable de télécharger le fichier. Raison: {err}"
	,"Unable to verify password recovery token":"Incapable de vérifier le jeton pour récupération de mot de passe"
	,"Unable to verify token":"Incapable de vérifier le jeton"
	,"Uncategorized":"Sans catégorie"
	,"Unknown Filter":"Filtre inconnu"
	,"Unknown List":"Liste inconnue"
	,"Unknown Transform":"Transformation inconnue"
	,"Unknown import profile type: {type}":"Type de profil d'importation inconnu: {type}"
	,"Unknown schema: {name}":"Schème inconnu: {name}"
	,"Unknown type for help document: {docId}":"Document d'aide avec type inconnu: {docId}"
	,"Unsupported Browser":"Fureteur incompatible"
	//no longer in use: "Unsupported Browser"
	,"Updated document with id: {id}":"Mise-à-jour du document: {id}"
	,"Upgrade Json Application Started":"Début de l'application de mise-à-jour JSON"
	,"Upload":"Télécharger"
	,"Upload Media Directory Listing":"Liste du répertoire de fichiers médiatiques"
	,"Upload service can not be reached. Unable to submit a related document.":"Le service de téléchargement n'est pas disponible."
	,"User":"Usager"
	,"User Agreement":"Entente de l'utilisateur"
	,"User Agreement and Terms of Service":"Entente de l'utilisateur et conditions d'utilisation"
	,"User Creation":"Creation d'un utilisateur"
	,"User Questionnaire":"Questionnaire de l'utilisateur"
	,"User Registration":"Enregistrement de l'utilisateur"
	,"User agreement has changed. You must accept before you can authenticate.":"L'entente de l'utilisateur a été mise à jour. Vous devez accepter la nouvelle version avant de procéder."
	,"User created but unable to log in: ":"Le nouvel usager fut créé, mais il est impossible d'ouvrir la session."
	,"User created successfully.":"Utilisateur créé"
	,"User name should have at least 3 characters":"Le nom d'usager devrait avoir au moins 3 caractères"
	,"User refused agreement":"L'utilisateur a rejeté l'entente"
	,"User registration initiated. Check for e-mail to complete user creation":"L'enregistrement de l'utilisateur a débuté. Vérifiez vos courriels pour continuer le processus."
	,"Validated E-mail":"Adresse courriel vérifiée"
	,"Verification":"Vérification"
	,"Verify":"Vérifier"
	,"Verify Password":"Vérifiez le mot de passe"
	,"Verifying token":"Vérification du jeton"
	,"View":"Afficher"
	,"View Media":"Visualiser le Média"
	,"View Original":"Visionner le document original"
	,"View Submission":"Visionner la soumission"
	,"View Submitted":"Visionner la soumission"
	,"Warning":"Attention"
	,"Warning on Database Submissions":"Avertissement à la base de données des soumissions"
	,"Welcome":"Bienvenue"
	,"Yes":"Oui"
	//no longer in use: "Yes"
	,"You are about to delete this document. Do you want to proceed?":"Voulez-vous vraiment supprimer ce document?"
	,"You are about to leave this page. Do you wish to continue?":"Vous quittez cette page. Voulez-vous continuer?"
	,"You must agree to the User Agreement before creating a user.":"Vous devez accepter l'entente de l'utilisateur avant d'enregistrer un nouvel utilisateur"
	,"You must enter a valid function":"Vous devez soumettre une fonction valide"
	,"You must first load the database info.":"Vous devez en premier charger l'information de la base données"
	,"You must first load the media directory listing.":"Vous devez en premier charger la liste du répertoire des fichiers médiatiques"
	,"You must first log in to create a new document.":"Vous devez ouvrir une session avant de créer un document."
	,"You must leave the atlas to view this file.":"Vous devez quitter l'atlas pour accéder à ce fichier."
	,"You must provide a display name":"Vous devez préciser un nom d'affichage"
	,"You must provide a message":"Vous devez fournir un message"
	,"You must provide a password":"Vous devez préciser un mot de passe"
	,"You must provide contact information":"Vous devez fournir vos coordonnées"
	,"You must provide field: {label}":"Vous devez précisez le champ: {label}"
	,"You must select a file":"Vous devez précisez un fichier"
	,"Your browser is not supported by this web site.":"Votre fureteur est incompatible avec ce site"
	,"Your file was uploaded and will become available when it has been approved.":"Votre fichier est téléchargé. Il sera disponible lorsqu'un adminitrateur l'aura approuvé"
	,"Your message was sent":"Votre message est en route"
	,"Your password is too short":"Votre mot de passe est trop court"
	,"Zoom In":"Rapprocher la carte"
	,"Zoom Out":"Eloigner la carte"
	,"a Checkbox":"une Boîte"
	,"a Number":"un Chiffre"
	,"a String":"une Chaîne de Caractères"
	,"an Array":"une Chaîne"
	,"an Object":"un Objet"
	,"an image":"une image"
	,"confirm password":"vérifier le mot de passe"
	,"creation":"création"
	,"csv":"csv"
	,"deletion":"supression"
	,"display name":"nom d'affichage"
	,"e-mail address":"adresse courriel"
	,"empty":"vide"
	,"geojson":"geojson"
	,"id":"id"
	//no longer in use: "id"
	,"is":"est"
	,"main site":"page principale"
	,"on":"sur"
	,"password":"mot de passe"
	,"search the atlas":"recherche de l'atlas"
	,"top":"en haut"
	,"update":"mise à jour"
	,"user name":"Nom d'usager"
	,"{count} document(s)":"{count} document(s)"
	,"{count} document(s) modified.":"{count} document(s) modifiés."
	//no longer in use: "{count} document(s) modified."
	,"{docId} deleted":"{docId} supprimé"
	,"{docId} transformed and saved":"{docId} transformé et sauvegardé"
	,"{index}/{count}":"{index}/{count}"
	,"{label} definition ({key}) already exists - not loaded or updated":"Définition {label} ({key}) existe déjà - ignorée"
	,"No documents found.": "Aucun document n'a été trouvé."
	,"File Upload": "Téléchargement de fichiers"
	,"Record Audio": "Enregistrer l'audio"
	,"Record Video": "Enregistrer une vidéo"
	,"Skip to content": "Omettre la navigation"
	,"Maximum file size allowed": "Taille maximale du fichier autorisée"
});

if( $ && $.datepicker ) {
	var regional = {
		renderer: $.ui.datepicker.defaultRenderer
		,monthNames: [
			'Janvier'
			,'Février'
			,'Mars'
			,'Avril'
			,'Mai'
			,'Juin'
			,'Juillet'
			,'Août'
			,'Septembre'
			,'Octobre'
			,'Novembre'
			,'Décembre'
		]
		,monthNamesShort: [
			'Jan'
			,'Fév'
			,'Mar'
			,'Avr'
			,'Mai'
			,'Jun'
			,'Jul'
			,'Aoû'
			,'Sep'
			,'Oct'
			,'Nov'
			,'Déc'
		]
		,dayNames: [
			'Dimanche'
			,'Lundi'
			,'Mardi'
			,'Mercredi'
			,'Jeudi'
			,'Vendredi'
			,'Samedi'
		]
		,dayNamesShort: [
			'Dim'
			,'Lun'
			,'Mar'
			,'Mer'
			,'Jeu'
			,'Ven'
			,'Sam'
		]
		,dayNamesMin: [
			'Di'
			,'Lu'
			,'Ma'
			,'Me'
			,'Je'
			,'Ve'
			,'Sa'
		]
		,dateFormat: 'dd/mm/yyyy'
		,firstDay: 1
		,prevText: '&#x3c;Préc'
		,prevStatus: 'Voir le mois précédent'
		,prevJumpText: '&#x3c;&#x3c;'
		,prevJumpStatus: 'Voir l\'année précédent'
		,nextText: 'Suiv&#x3e;'
		,nextStatus: 'Voir le mois suivant'
		,nextJumpText: '&#x3e;&#x3e;'
		,nextJumpStatus: 'Voir l\'année suivante'
		,currentText: 'Courant'
		,currentStatus: 'Voir le mois courant'
		,todayText: 'Aujourd\'hui'
		,todayStatus: 'Voir aujourd\'hui'
		,clearText: 'Effacer'
		,clearStatus: 'Effacer la date sélectionnée'
		,closeText: 'Fermer'
		,closeStatus: 'Fermer sans modifier'
		,yearStatus: 'Voir une autre année'
		,monthStatus: 'Voir un autre mois'
		,weekText: 'Sm'
		,weekStatus: 'Semaine de l\'année'
		,dayStatus: '\'Choisir\' le DD d MM'
		,defaultStatus: 'Choisir la date'
		,isRTL: false
	};

	$.datepicker.setDefaults( regional );
};
	
})(jQuery,nunaliit2);