package ca.carleton.gcrc.pgSync;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

import org.jdbi.v3.core.Handle;
import org.jdbi.v3.core.Jdbi;
import org.jdbi.v3.core.statement.Update;
import org.jdbi.v3.postgres.PostgresPlugin;
import org.json.JSONArray;
import org.json.JSONObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import ca.carleton.gcrc.couch.app.Attachment;
import ca.carleton.gcrc.couch.app.impl.DocumentCouchDb;
import ca.carleton.gcrc.couch.client.CouchDb;
import ca.carleton.gcrc.couch.client.CouchDesignDocument;
import ca.carleton.gcrc.couch.client.CouchQuery;
import ca.carleton.gcrc.couch.client.CouchQueryResults;

public class PgSyncActions {
	final protected Logger logger = LoggerFactory.getLogger(this.getClass());
	private Jdbi jdbi;
	private CouchDb couchDb;
	private CouchDesignDocument atlasDesign;
	private Map<String, Integer> layerCache;
	private List<String[]> n2Sources;
	private List<String[]> n2Relations;
	private Map<String, Map<String, Map<String, Object>>> schemas;

	public PgSyncActions(String pgConnectString, String pgUser, String pgPass, CouchDb couchDb,
			CouchDesignDocument atlasDesign) {
		this.couchDb = couchDb;
		this.atlasDesign = atlasDesign;
		if (pgUser == null || pgUser.isEmpty() || pgPass == null || pgPass.isEmpty()) {
			jdbi = Jdbi.create(pgConnectString)
					.installPlugin(new PostgresPlugin());
		} else {
			jdbi = Jdbi.create(pgConnectString, pgUser, pgPass)
					.installPlugin(new PostgresPlugin());
		}

	}

	public void recreateBaseN2Tables() {
		jdbi.useHandle(handle -> {
			handle.execute("DROP SCHEMA IF EXISTS n2 CASCADE");
			handle.execute("CREATE SCHEMA IF NOT EXISTS n2");
			handle.execute("CREATE EXTENSION IF NOT EXISTS postgis");
		});

		jdbi.useHandle(handle -> {
			// Should we just truncate these tables instead? The don't change right?
			handle.execute("DROP TABLE IF EXISTS n2.docs_docs;");
			handle.execute("DROP TABLE IF EXISTS n2.docs_layers;");
			handle.execute("DROP TABLE IF EXISTS n2.layers;");
			handle.execute("DROP TABLE IF EXISTS n2.docs CASCADE;");
			handle.execute("CREATE TABLE n2.docs (" +
					"    id character varying(255) PRIMARY KEY,\n" +
					"    nunaliit_rev character varying(255),\n" +
					"    nunaliit_schema character varying(255),\n" +
					"    nunaliit_geom geometry,\n" +
					"    nunaliit_source character varying(255) REFERENCES n2.docs(id),\n " +
					"    nunaliit_values jsonb\n" +
					");");
			handle.execute("CREATE TABLE n2.layers (" +
					"    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,\n" +
					"    name text NOT NULL\n" +
					");");
			handle.execute("CREATE TABLE n2.docs_layers (" +
					"doc_id character varying(255) NOT NULL REFERENCES n2.docs(id) ON UPDATE CASCADE ON DELETE CASCADE,\n"
					+
					"layer_id INT NOT NULL REFERENCES n2.layers(id) ON UPDATE CASCADE ON DELETE CASCADE,\n" +
					"PRIMARY KEY(doc_id, layer_id)\n" +
					");");
			handle.execute("CREATE TABLE n2.docs_docs (" +
					"src_id character varying(255) NOT NULL REFERENCES n2.docs(id) ON UPDATE CASCADE ON DELETE CASCADE,\n"
					+
					"tgt_id character varying(255) NOT NULL REFERENCES n2.docs(id) ON UPDATE CASCADE ON DELETE CASCADE,\n"
					+
					"PRIMARY KEY(src_id, tgt_id)\n" +
					");");
		});

	}

	public void syncAllDocs() throws Exception {
		deletePgData();
		CouchQueryResults results = fetchCouchSchemaInfo();
		createPgTables(results);

		layerCache = new HashMap<String, Integer>();
		n2Sources = new ArrayList<>();
		n2Relations = new ArrayList<>();

		// Loop over schemas and sync docs to postgres
		for (String schemaName : schemas.keySet()) {
			CouchQuery query = new CouchQuery();
			query.setViewName("nunaliit-schema");
			query.setStartKey(schemaName);
			query.setEndKey(schemaName);
			query.setIncludeDocs(false);

			CouchQueryResults docResults = atlasDesign.performQuery(query);
			syncDocsForSchema(docResults, schemaName);
		}
		insertLinks();
		logger.info("Done syncing all docs to postgres");
	}

	public void reloadDoc(String docId) {
		try {
			DocumentCouchDb doc = DocumentCouchDb.documentFromCouchDb(couchDb, docId);
			String docSchema = doc.getSchema();
			if (!schemas.containsKey(docSchema)) {
				logger.error("Can't sync document " + docId + " with postgres, schema " + docSchema + " not syncable");
			}
			jdbi.useHandle(h -> {
				h.execute("DELETE FROM n2.docs WHERE id = ?", docId);
				insertDoc(doc, docSchema, h);
			});
			logger.info("Doc " + docId + " synced to postgres DB");
		} catch (Exception e) {
			logger.error("Error attempting to sync doc with id " + docId + " to postgres DB", e);
		}
	}

	public DocumentCouchDb getDocument(String docId) throws Exception {
		return DocumentCouchDb.documentFromCouchDb(couchDb, docId);
	}

	private void deletePgData() {
		jdbi.useHandle(handle -> {
			handle.execute("TRUNCATE n2.docs RESTART IDENTITY CASCADE;");
			handle.execute("TRUNCATE n2.layers RESTART IDENTITY CASCADE;");
		});
	}

	private CouchQueryResults fetchCouchSchemaInfo() throws Exception {
		CouchQuery schemaQuery = new CouchQuery();
		schemaQuery.setViewName("schemas-root");
		schemaQuery.setIncludeDocs(true);
		return atlasDesign.performQuery(schemaQuery);
	}

	private void createPgTables(CouchQueryResults couchDocs) {
		schemas = new HashMap<String, Map<String, Map<String, Object>>>();
		for (JSONObject row : couchDocs.getRows()) {
			String docId = row.optString("id");
			String key = row.optString("key");
			if (null != docId && !docId.startsWith("org.nunaliit")) {
				JSONArray exportArray = null;
				Map<String, Map<String, Object>> pgCols = new HashMap<String, Map<String, Object>>();
				if (row.has("doc") && row.getJSONObject("doc").has("pgExport")) {
					exportArray = new JSONArray(row.getJSONObject("doc").getJSONArray("pgExport"));
				} else {
					logger.info("Missing pgExport for " + docId);
					continue;
				}

				String newTblName = "n2." + key;

				if (exportArray != null) {
					List<String> newRefTables = new ArrayList<String>();
					for (Object a : exportArray) {
						if (!(a instanceof JSONObject)) {
							logger.error("attributes not readable for pg sync for schema " + docId);
							continue;
						}
						JSONObject att = (JSONObject) a;
						if (!att.has("field") || !att.has("type")) { // skip non-field attributes
							continue;
						}
						String k = att.getString("field");
						String aType = att.getString("type");
						if (aType.equalsIgnoreCase("string")) {
							HashMap<String, Object> colDef = new HashMap<String, Object>();
							colDef.put("pgType", "TEXT");
							pgCols.put(k, colDef);
						} else if (aType.equalsIgnoreCase("localized")) {
							String loc_type = "table";
							String[] loc_langs = new String[0];
							if (att.has("strategy") && att.getString("strategy").equals("column")) {
								if (att.has("language_codes") && att.getJSONArray("language_codes").length() > 0) {
									loc_type = "column";
									loc_langs = new String[att.getJSONArray("language_codes").length()];
									for (int i = 0; i < att.getJSONArray("language_codes").length(); i++) {
										loc_langs[i] = att.getJSONArray("language_codes").getString(i);
									}
								} else {
									logger.error(
											"Localized strategy columns requires language codes definition. Reverting to table strategy.");
								}

							}
							if (loc_type.equals("table")) {
								HashMap<String, Object> colDef = new HashMap<String, Object>();
								colDef.put("pgType", "REF");
								colDef.put("n2Type", "localized");
								String joinTbl = newTblName + "_" + k + "_localized";
								colDef.put("joinName", joinTbl);
								pgCols.put(k, colDef);
								newRefTables.add("DROP TABLE IF EXISTS " + joinTbl);
								newRefTables.add("CREATE TABLE " + joinTbl + " (" +
										"id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,\n" +
										"doc_id character varying(255) NOT NULL REFERENCES n2.docs(id) ON UPDATE CASCADE ON DELETE CASCADE,\n"
										+
										"text text NOT NULL,\n" +
										"code VARCHAR(10) NOT NULL\n" +
										");");
							} else if (loc_type.equals("column")) {
								HashMap<String, Object> colDef = new HashMap<String, Object>();
								colDef.put("pgType", "TEXT");
								colDef.put("n2Type", "localized");
								colDef.put("languageCodes", loc_langs);
								pgCols.put(k, colDef);
							}
						} else if (aType.equalsIgnoreCase("date")) {
							HashMap<String, Object> colDef = new HashMap<String, Object>();
							colDef.put("pgType", "TEXT");
							colDef.put("n2Type", "date");
							pgCols.put(k, colDef);
						} else if (aType.equalsIgnoreCase("reference")) {
							logger.error("PG Sync does not support reference field, found in schema: " + key);
							logger.error(att.toString());
							continue;
						} else if (aType.equalsIgnoreCase("array")) {
							String elType = att.getString("elementType");
							HashMap<String, Object> colDef = new HashMap<String, Object>();
							if (elType.equals("string")) {
								colDef.put("pgType", "TEXT[]");
							} else {
								logger.error("PG Sync does not support array fields with subtype " + elType
										+ ", found in schema: " + key);
								logger.error(att.toString());
								continue;
							}
							pgCols.put(k, colDef);
						} else if (aType.equalsIgnoreCase("tag")) {
							HashMap<String, Object> colDef = new HashMap<String, Object>();
							String refTbl = "n2." + k;
							String joinTbl = newTblName + "_" + k;
							colDef.put("n2Type", "TAG");
							colDef.put("pgType", "REF");
							colDef.put("pgRefType", "TEXT");
							colDef.put("tableName", refTbl);
							colDef.put("joinName", joinTbl);
							pgCols.put(k, colDef);
							newRefTables.add("DROP TABLE IF EXISTS " + joinTbl);
							newRefTables.add("DROP TABLE IF EXISTS " + refTbl);
							newRefTables.add("CREATE TABLE " + refTbl +
									" (id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY," +
									"  value TEXT);");
							newRefTables.add("CREATE TABLE " + newTblName + "_" + k + " (" +
									"doc_id character varying(255) NOT NULL REFERENCES n2.docs(id) ON UPDATE CASCADE ON DELETE CASCADE,\n"
									+
									"link_id INT NOT NULL REFERENCES n2." + k
									+ "(id) ON UPDATE CASCADE ON DELETE CASCADE,\n" +
									"PRIMARY KEY(doc_id, link_id)\n" +
									");");
						} else if (aType.equalsIgnoreCase("selection")) {
							HashMap<String, Object> colDef = new HashMap<String, Object>();
							colDef.put("pgType", "TEXT");
							pgCols.put(k, colDef);
						} else if (aType.equalsIgnoreCase("checkbox")) {
							HashMap<String, Object> colDef = new HashMap<String, Object>();
							colDef.put("pgType", "BOOLEAN");
							pgCols.put(k, colDef);
						} else if (aType.equalsIgnoreCase("checkbox_group")) {
							JSONArray boxes = att.getJSONArray("checkboxes");
							for (Object box : boxes) {
								if (!(box instanceof JSONObject)) {
									logger.error("Expected JSONObject in checkboxes array, skipping");
									continue;
								}
								JSONObject jsonBox = (JSONObject) box;
								HashMap<String, Object> colDef = new HashMap<String, Object>();
								String boxKey = jsonBox.getString("id");
								colDef.put("pgType", "BOOLEAN");
								pgCols.put(boxKey, colDef);
							}
						} else if (aType.equalsIgnoreCase("file")) {
							logger.error("PG Sync does not support file field, found in schema: " + key);
							logger.error(att.toString());
							continue;
						} else if (aType.equalsIgnoreCase("title")) {
							logger.error("PG Sync does not support title field, found in schema: " + key);
							logger.error(att.toString());
							continue;
						} else if (aType.equalsIgnoreCase("geometry")) {
							HashMap<String, Object> colDef = new HashMap<String, Object>();
							colDef.put("pgType", "geometry");
							pgCols.put(k, colDef);
						} else if (aType.equalsIgnoreCase("hover_sound")) {
							logger.error("PG Sync does not support hover_sound field, found in schema: " + key);
							logger.error(att.toString());
							continue;
						} else if (aType.equalsIgnoreCase("nunaliit_key_media_ref")) {
							logger.error("PG Sync does not support nunaliit_key_media_ref field, found in schema: "
									+ key);
							logger.error(att.toString());
							continue;
						} else if (aType.equalsIgnoreCase("triple")) {
							logger.error("PG Sync does not support triple field, found in schema: " + key);
							logger.error(att.toString());
							continue;
						} else if (aType.equalsIgnoreCase("createdBy")) {
							logger.error("PG Sync does not support createdBy field, found in schema: " + key);
							logger.error(att.toString());
							continue;
						} else if (aType.equalsIgnoreCase("createdTime")) {
							logger.error("PG Sync does not support createdTime field, found in schema: " + key);
							logger.error(att.toString());
							continue;
						} else if (aType.equalsIgnoreCase("custom")) {
							logger.error("PG Sync does not support custom field, found in schema: " + key);
							logger.error(att.toString());
							continue;
						}
					}

					jdbi.useHandle(handle -> {
						String createTable = "CREATE TABLE " + newTblName + " (\n";
						List<String> fields = new ArrayList<String>();
						fields.add(
								"doc_id character varying(255) PRIMARY KEY REFERENCES n2.docs(id) ON UPDATE CASCADE ON DELETE CASCADE");

						for (String colName : pgCols.keySet()) {
							String pgType = (String) pgCols.get(colName).get("pgType");
							String n2Type = (String) pgCols.get(colName).get("n2Type");
							if (n2Type != null && n2Type.equals("localized") && pgType.equals("TEXT")) {
								String[] loc_langs = (String[]) pgCols.get(colName).get("languageCodes");
								for (String lang : loc_langs) {
									fields.add(colName + "_" + lang + " " + pgType);
								}
							} else if (!pgType.equals("REF")) {
								fields.add(colName + " " + pgType);
							}
						}
						createTable += String.join(", ", fields);
						createTable += ");";

						handle.execute("DROP TABLE IF EXISTS " + newTblName);
						handle.execute(createTable);
						for (String modTblStmt : newRefTables) {
							handle.execute(modTblStmt);
						}
					});
				}
				schemas.put(key, pgCols);
			}
		}
	}

	private void insertLinks() {
		jdbi.useHandle(h -> {
			for (String[] n2src : n2Sources) {
				Integer cnt = h.select("SELECT COUNT(id) FROM n2.docs WHERE id = ?", n2src[1]).mapTo(Integer.class)
						.one();
				if (cnt < 1) {
					logger.error("Can't insert nunaliit_source target " + n2src[1]
							+ " because document with that id does not exist");
				} else {
					h.execute("UPDATE n2.docs SET nunaliit_source = ? WHERE id = ?", n2src[1], n2src[0]);
				}
			}
			for (String[] n2rel : n2Relations) {
				h.execute("INSERT INTO n2.docs_docs (src_id, tgt_id) VALUES (?, ?)", n2rel[0], n2rel[1]);
			}
		});
	}

	private void insertDoc(DocumentCouchDb doc, String schemaName, Handle h) throws Exception {
		if (doc != null && doc.getJSONObject() != null) {
			String docId = doc.getId();
			String geom = null;
			Attachment geomOrig = null;
			for (Attachment a : doc.getAttachments()) {
				if (a.getName().startsWith("nunaliit2_geom_") && a.getName().endsWith("_original")) {
					geomOrig = a;
					break;
				}
			}
			if (geomOrig != null) {
				BufferedReader in = new BufferedReader(
						new InputStreamReader(geomOrig.getInputStream()));
				String inputLine;
				StringBuffer geomContent = new StringBuffer();
				while ((inputLine = in.readLine()) != null) {
					geomContent.append(inputLine);
				}
				in.close();
				geom = geomContent.toString();
			} else if (doc.getJSONObject().has("nunaliit_geom")) {
				JSONObject nunaliit_geom = doc.getJSONObject().optJSONObject("nunaliit_geom", null);
				if (nunaliit_geom != null) {
					geom = nunaliit_geom.optString("wkt", null);
				}
			}
			try {
				h.execute("INSERT INTO n2.docs " +
						"(id, nunaliit_rev, nunaliit_schema, nunaliit_values, nunaliit_geom) values " +
						"(?, ?, ?, CAST(? AS jsonb), ST_GeomFromText(?))",
						docId, doc.getRevision(), doc.getSchema(), doc.getJSONObject().toString(), geom);

				for (String l : doc.getLayers()) {
					Integer layerId;
					if (layerCache.containsKey(l)) {
						layerId = layerCache.get(l);
					} else {
						layerId = h.select("INSERT INTO n2.layers (name) values (?) returning id", l)
								.mapTo(Integer.class).one();
						layerCache.put(l, layerId);
					}
					h.execute("INSERT INTO n2.docs_layers (doc_id, layer_id) VALUES (?, ?)", docId,
							layerId);
				}

				if (doc.getJSONObject().has("nunaliit_source")) {
					JSONObject nsrc = doc.getJSONObject().getJSONObject("nunaliit_source");
					if (nsrc.has("doc")) {
						String tid = nsrc.getString("doc");
						String[] idPair = { docId, tid };
						n2Sources.add(idPair);
					}
				}

				if (doc.getJSONObject().has(("nunaliit_relations"))) {
					JSONArray nrels = doc.getJSONObject().getJSONArray("nunaliit_relations");
					for (Object nrelObj : nrels) {
						if (!(nrelObj instanceof JSONObject)) {
							logger.error("Doc " + docId
									+ " has malformed nunaliit_relations, expected array of objects");
							continue;
						}
						JSONObject rel = (JSONObject) nrelObj;
						String[] link = { docId, rel.getString("doc") };
						n2Relations.add(link);
					}
				}

				if (doc.getJSONObject().has(schemaName)) {
					Map<String, Map<String, Object>> pgInfo = schemas.get(schemaName);
					String insStatment = "INSERT INTO n2." + schemaName;
					List<String> fields = new ArrayList<String>();
					List<String> stmtVals = new ArrayList<String>();
					Map<String, String> fieldTypes = new HashMap<String, String>();
					Map<String, Object> bindVals = new HashMap<String, Object>();
					JSONObject attributeJsonObject = doc.getJSONObject().getJSONObject(schemaName);
					for (String colName : pgInfo.keySet()) {
						if (attributeJsonObject.has(colName)) {
							String colPgType = (String) pgInfo.get(colName).get("pgType");
							String refTbl = (String) pgInfo.get(colName).get("tableName");
							String joinName = (String) pgInfo.get(colName).get("joinName");
							String n2Type = (String) pgInfo.get(colName).get("n2Type");
							if (colPgType.equals("REF")) {
								if (n2Type.equals("TAG")) {
									JSONObject tagObj = attributeJsonObject.getJSONObject(colName);
									JSONArray tagVals = tagObj.getJSONArray("tags");
									Set<String> uTagVals = new HashSet<String>();
									for (Object tag : tagVals) {
										String t = (String) tag;
										uTagVals.add(t);
									}
									for (Object tag : uTagVals) {
										Integer refId;
										Optional<Integer> optRefId = h
												.select("SELECT id FROM " + refTbl
														+ " WHERE LOWER(value) = LOWER(?)",
														tag)
												.mapTo(Integer.class)
												.findFirst();
										if (optRefId.isPresent()) {
											refId = optRefId.get();
										} else {
											refId = h
													.select("INSERT INTO " + refTbl
															+ "(value) VALUES (?) returning id",
															tag)
													.mapTo(Integer.class)
													.one();
										}
										h.execute(
												"INSERT INTO " + joinName
														+ " (doc_id, link_id) VALUES (?, ?)",
												docId, refId);
									}
								} else if (n2Type.equals("localized")) {
									Object val = attributeJsonObject.get(colName);
									String locInsQ = "INSERT INTO " + joinName
											+ " (doc_id, text, code) VALUES (?, ?, ?)";
									if (val instanceof String) { // no localized object
										String text = val.toString();
										h.execute(locInsQ, docId, text, "en");
									} else if (val instanceof JSONObject) {
										JSONObject locVal = (JSONObject) val;
										for (String lk : locVal.keySet()) {
											if (lk.equals("nunaliit_type")) {
												continue;
											}
											h.execute(locInsQ, docId, locVal.get(lk).toString(), lk.toString());
										}
									}
								}
							} else if (colPgType.equals("TEXT") && n2Type != null
									&& n2Type.equals("localized")) {
								Object val = attributeJsonObject.get(colName);
								String[] loc_langs = (String[]) pgInfo.get(colName).get("languageCodes");
								for (String lang : loc_langs) {
									String langColName = colName + "_" + lang;
									fields.add(langColName);
									stmtVals.add(":" + langColName);
									if (val instanceof String) { // no localized object
										String text = val.toString();
										bindVals.put(langColName, text);
									} else if (val instanceof JSONObject) {
										JSONObject locVal = (JSONObject) val;
										String text = locVal.optString("lang");
										bindVals.put(langColName, text);
									}
								}
							} else {
								fields.add(colName);
								stmtVals.add(":" + colName);
								if (pgInfo.get(colName).containsKey("n2Type")
										&& pgInfo.get(colName).get("n2Type").equals("date")) {
									Object val = attributeJsonObject.getJSONObject(colName).getString("date");
									bindVals.put(colName, val);
								} else if (colPgType.equals("TEXT")) {
									Object val = attributeJsonObject.get(colName).toString();
									bindVals.put(colName, val);
								} else if (colPgType.equals("TEXT[]")) {
									Object val = attributeJsonObject.get(colName);
									if (val instanceof JSONArray) {
										List<Object> vals = ((JSONArray) val).toList();
										fieldTypes.put(colName, "TextArray");
										if (vals.isEmpty()) {
											fields.remove(colName);
											stmtVals.remove(":" + colName);
										} else {
											bindVals.put(colName, vals);
										}
									} else {
										logger.error("Can't insert non-array value when expecting array: "
												+ val.toString());
									}
								} else {
									Object val = attributeJsonObject.get(colName);
									bindVals.put(colName, val);
								}
							}
						}
					}
					if (fields.size() > 0) {
						insStatment += " ( doc_id, " + String.join(", ", fields) + ") ";
						insStatment += " VALUES ( :doc_id, " + String.join(", ", stmtVals) + ")";
						Update u = h.createUpdate(insStatment);
						u.bind("doc_id", docId);
						for (String f : fields) {
							if (fieldTypes.containsKey(f) && fieldTypes.get(f).equals("TextArray")) {
								@SuppressWarnings("unchecked")
								List<String> bvList = ((List<Object>) bindVals.get(f)).stream()
										.map(v -> v.toString()).collect(Collectors.toList());
								;
								u.bindArray(f, String.class, bvList);
							} else {
								u.bind(f, bindVals.get(f));
							}
						}
						u.execute();
					} else {
						logger.info("Nothing to insert for doc " + docId);
					}
				}
			} catch (Exception e) {
				logger.error("Error inserting document", e);
				logger.error(doc.getJSONObject().toString());
			}
		} else {
			logger.error("Failed to fetch doc with id " + doc.getId());
		}
	}

	private void syncDocsForSchema(CouchQueryResults schemaDocs, String schemaName) throws Exception {
		jdbi.useHandle(h -> {
			for (JSONObject row : schemaDocs.getRows()) {
				String docId = row.optString("id");
				DocumentCouchDb doc = DocumentCouchDb.documentFromCouchDb(couchDb, docId);
				insertDoc(doc, schemaName, h);
			}
		});
	}
}
